In [65]:
from pathlib import Path

from dotenv import load_dotenv
from qdrant_client import QdrantClient
from qdrant_client.models import Distance, VectorParams, PointStruct
import cohere
import pandas as pd
import os

load_dotenv()

True

Read items dataset

In [66]:
df_items=pd.read_json("../../data/meta_Appliances_with_category_ratings_100.jsonl",lines=True)

In [67]:
df_items

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together
0,Amazon Home,HERISUN 100 Disposable Coffee Filters for Sing...,4.4,360,[【Good Fits in All Refillable Pods】K cup paper...,[],7.99,[{'thumb': 'https://m.media-amazon.com/images/...,[],HERISUN,"[Small Appliance Parts & Accessories, Coffee &...",{'Product Dimensions': '4.7 x 2.5 x 2.5 inches...,B0BJKNMKRP,NaN
1,Tools & Home Improvement,Large Capacity Egg Holder For Refrigerator - 3...,4.6,1285,[Auto Rolling Egg Holder: Egg container keeps ...,[Large Capacity Egg Container For Refrigerator...,24.99,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Honest review of egg holder for fr...,TOGOO,"[Appliances, Parts & Accessories, Refrigerator...","{'Material': 'Plastic', 'Color': 'Clear', 'Bra...",B0B2NP5QQT,NaN
2,Amazon Home,Ritadeshop Stove Top Burner Covers Black Marbl...,4.3,155,[Burner covers offer more counter space and co...,[Set of 2.Made of Tinplate.Size: Outer measure...,22.99,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Ritadeshop Large Black Marble Burn...,Ritadeshop,"[Appliances, Parts & Accessories, Range Parts ...",{'Package Dimensions': '20.63 x 12.03 x 1.19 i...,B0BKFVJ2RD,NaN
3,Tools & Home Improvement,DISNIMO Boho Style Refrigerator Door Handle Co...,4.5,204,[【Perfect Size】: The Size of one cover is 16.1...,[],11.99,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Metonsto Refrigerator Handle Cover...,DISNIMO,"[Appliances, Parts & Accessories, Refrigerator...","{'Material': 'Polyester', 'Brand': 'DISNIMO', ...",B09KC11XYV,NaN
4,Appliances,"HiCOZY Dual-Mode Nugget Ice Maker Countertop, ...",4.2,201,"[Quicool Technology, Fast Ice Making: HiCOZY u...",[],399.99,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'Returned', 'url': 'https://www.ama...",Hicozy,"[Appliances, Refrigerators, Freezers & Ice Mak...","{'Brand': 'HiCOZY', 'Model Name': 'Nugget Ice ...",B0BYZ86N13,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1509,Tools & Home Improvement,Stove Cover for Samsung Gas Range with 2pcs Ga...,3.6,121,[【Hassle-free Purchase】Please refer to the siz...,[],17.99,[{'thumb': 'https://m.media-amazon.com/images/...,[],BVSIAONG,"[Appliances, Parts & Accessories, Range Parts ...","{'Manufacturer': 'BVSIAONG', 'Part Number': 'B...",B0BMVQBK84,NaN
1510,Industrial & Scientific,"Portable Ice Maker, 26Lbs/24H Self-Cleaning Ic...",4.2,399,"[Quick and Powerful: Within only 6 minutes, yo...",[Enjoy fresh homemade ice anytime with this po...,NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],KINGSWERE,"[Appliances, Refrigerators, Freezers & Ice Mak...",{'Package Dimensions': '14.8 x 13.5 x 11 inche...,B09X6XVRBF,NaN
1511,Tools & Home Improvement,Sealegend 2 Pieces Dryer Vent Cleaner Kit New ...,4.2,127,[【New Upgrade】According to customer feedback o...,[],13.95,[{'thumb': 'https://m.media-amazon.com/images/...,[],Sealegend,"[Appliances, Parts & Accessories, Dryer Parts ...","{'Manufacturer': 'Sealegend', 'Part Number': '...",B0CFQGFBPM,NaN
1512,Industrial & Scientific,"Nugget Ice Maker Countertop, Crushed Chewable ...",4.3,1360,[FAST ＆ EFFICIENT ICE MAKER: With a water tank...,[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],FOOING,"[Appliances, Refrigerators, Freezers & Ice Mak...",{'Product Dimensions': '15.4 x 13.07 x 10.19 i...,B0CFLQ4FM6,NaN
1513,Tools & Home Improvement,"Front Load Washer Door Prop, Magnetic Washing ...",4.5,156,[NOTE package contain: 1 PCS 17.2 inch White C...,[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],NOTLZPLS,"[Appliances, Parts & Accessories, Washer Parts...","{'Manufacturer': 'NOTLZPLS', 'Part Number': 'N...",B094J4JSPJ,NaN

In [68]:
list(df_items["features"].items())[0]

(0,
 ['【Good Fits in All Refillable Pods】K cup paper filters are compatible with all standard reusable single cup filters (not included), perfect size gives you perfect brew experience',
  '【Space for Coffee Flow Through】K cup disposable filters must be shorter than refillable pods, leave sufficient space for coffee come out. Keeps grounds out of coffee cup',
  '【Improved Coffee flavor】Remove oils and sediments, full brewing and effective filtration thinner filter papers ensure origina flavor of the coffee',
  '【Save Money and Time】Reduces k cup waste and save money, easy clean up, enjoy your favorite coffee, excellent for your personal enjoyment',
  '【No Blowouts】Last without tearing though, absorbs water so coffee liquid can flow through. Prevent coffee grinds from seeping from filter'])

In [69]:
list(df_items["images"].items())[0]

(0,
 [{'thumb': 'https://m.media-amazon.com/images/I/51tjs-IoCeL._AC_US75_.jpg',
   'large': 'https://m.media-amazon.com/images/I/51tjs-IoCeL._AC_.jpg',
   'variant': 'MAIN',
   'hi_res': 'https://m.media-amazon.com/images/I/717EWI9-gIL._AC_SL1500_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/51nCErqrMZL._AC_US75_.jpg',
   'large': 'https://m.media-amazon.com/images/I/51nCErqrMZL._AC_.jpg',
   'variant': 'PT01',
   'hi_res': 'https://m.media-amazon.com/images/I/71KwR0X8RnL._AC_SL1500_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/51U2t3qKPuL._AC_US75_.jpg',
   'large': 'https://m.media-amazon.com/images/I/51U2t3qKPuL._AC_.jpg',
   'variant': 'PT02',
   'hi_res': 'https://m.media-amazon.com/images/I/71pv1E0ic5L._AC_SL1500_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/41W0nbQ3BYL._AC_US75_.jpg',
   'large': 'https://m.media-amazon.com/images/I/41W0nbQ3BYL._AC_.jpg',
   'variant': 'PT03',
   'hi_res': 'https://m.media-amazon.com/images/I/71hXD5mVgXL._AC_SL1500_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/41qIdwZeLcL._AC_US75_.jpg',
   'large': 'https://m.media-amazon.com/images/I/41qIdwZeLcL._AC_.jpg',
   'variant': 'PT04',
   'hi_res': 'https://m.media-amazon.com/images/I/711V8lwLS6L._AC_SL1500_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/51rUcFB6JcL._AC_US75_.jpg',
   'large': 'https://m.media-amazon.com/images/I/51rUcFB6JcL._AC_.jpg',
   'variant': 'PT05',
   'hi_res': 'https://m.media-amazon.com/images/I/71NCpj6KzkL._AC_SL1500_.jpg'}])

Preprocess titles and features

In [70]:
def preprocess_description(row):
    return f"{row["title"]}{" ".join(row["features"])}"

In [71]:
def extract_first_large_image(row):
    return row["images"][0].get("large","")

In [72]:
df_items["description"] = df_items.apply(preprocess_description, axis=1)
df_items["images"] = df_items.apply(extract_first_large_image, axis=1)

In [73]:
df_items.head()

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together
0,Amazon Home,HERISUN 100 Disposable Coffee Filters for Sing...,4.4,360,[【Good Fits in All Refillable Pods】K cup paper...,HERISUN 100 Disposable Coffee Filters for Sing...,7.99,https://m.media-amazon.com/images/I/51tjs-IoCe...,[],HERISUN,"[Small Appliance Parts & Accessories, Coffee &...",{'Product Dimensions': '4.7 x 2.5 x 2.5 inches...,B0BJKNMKRP,NaN
1,Tools & Home Improvement,Large Capacity Egg Holder For Refrigerator - 3...,4.6,1285,[Auto Rolling Egg Holder: Egg container keeps ...,Large Capacity Egg Holder For Refrigerator - 3...,24.99,https://m.media-amazon.com/images/I/41PG5Y6cDM...,[{'title': 'Honest review of egg holder for fr...,TOGOO,"[Appliances, Parts & Accessories, Refrigerator...","{'Material': 'Plastic', 'Color': 'Clear', 'Bra...",B0B2NP5QQT,NaN
2,Amazon Home,Ritadeshop Stove Top Burner Covers Black Marbl...,4.3,155,[Burner covers offer more counter space and co...,Ritadeshop Stove Top Burner Covers Black Marbl...,22.99,https://m.media-amazon.com/images/I/51x+0PiNQA...,[{'title': 'Ritadeshop Large Black Marble Burn...,Ritadeshop,"[Appliances, Parts & Accessories, Range Parts ...",{'Package Dimensions': '20.63 x 12.03 x 1.19 i...,B0BKFVJ2RD,NaN
3,Tools & Home Improvement,DISNIMO Boho Style Refrigerator Door Handle Co...,4.5,204,[【Perfect Size】: The Size of one cover is 16.1...,DISNIMO Boho Style Refrigerator Door Handle Co...,11.99,https://m.media-amazon.com/images/I/3195BBr20R...,[{'title': 'Metonsto Refrigerator Handle Cover...,DISNIMO,"[Appliances, Parts & Accessories, Refrigerator...","{'Material': 'Polyester', 'Brand': 'DISNIMO', ...",B09KC11XYV,NaN
4,Appliances,"HiCOZY Dual-Mode Nugget Ice Maker Countertop, ...",4.2,201,"[Quicool Technology, Fast Ice Making: HiCOZY u...","HiCOZY Dual-Mode Nugget Ice Maker Countertop, ...",399.99,https://m.media-amazon.com/images/I/31F1km7rww...,"[{'title': 'Returned', 'url': 'https://www.ama...",Hicozy,"[Appliances, Refrigerators, Freezers & Ice Mak...","{'Brand': 'HiCOZY', 'Model Name': 'Nugget Ice ...",B0BYZ86N13,NaN

In [74]:
list(df_items["description"].items())[0]

(0,
 'HERISUN 100 Disposable Coffee Filters for Single Serve 1.0 and 2.0 Coffee Filter Paper Use with Reusable K Cup Filter Pods (Natural)【Good Fits in All Refillable Pods】K cup paper filters are compatible with all standard reusable single cup filters (not included), perfect size gives you perfect brew experience 【Space for Coffee Flow Through】K cup disposable filters must be shorter than refillable pods, leave sufficient space for coffee come out. Keeps grounds out of coffee cup 【Improved Coffee flavor】Remove oils and sediments, full brewing and effective filtration thinner filter papers ensure origina flavor of the coffee 【Save Money and Time】Reduces k cup waste and save money, easy clean up, enjoy your favorite coffee, excellent for your personal enjoyment 【No Blowouts】Last without tearing though, absorbs water so coffee liquid can flow through. Prevent coffee grinds from seeping from filter')

Sample 50 items from the dataset

In [75]:
df_sample=df_items.sample(50, random_state=42)

In [76]:
len(df_sample)

50

In [77]:
data_to_embed = df_sample[["description","images","rating_number","price","average_rating","parent_asin"]].to_dict(orient="records")

In [78]:
data_to_embed

[{'description': "Gevi Household V2.0 Countertop Nugget Ice Maker | Self Cleaning Pellet Ice Machine | Open and Pour Water Refill | Store Ice Up to 24 Hours | Stainless Steel Housing | Fits Under Wall Cabinet | White【Nugget Ice】 Also known as Pellet ice or Chewblet ice. Unlike those hard ice cubes, nugget ice is made not only to cool down drinks but also to retain their flavor and provide chewable joy. Before you have to drive to chain stores for it, but now you can have it directly from your countertop whenever you like! 【Ice Ready Always】 Max 30Lbs ice in 24 hours, 4.8Lbs ice basket, 2.8L/3quarts water reservoir, extra thick insulation, auto ice refill, ice is always ready for you. 【Ultra Quiet】 Equipped with latest high performance compressor, muted exhaust fan and high precision ice making components, every effort is made to lower the noise and create an ultra quiet world of ice. 【Sleek Design】 Stainless steel housing, touch control panel, ice access from the front with Anti Dripping Lid, 16.9'' height fits perfectly under wall cabinet. 【100% Satisfaction Is Our Goal】 Gevi values your satisfaction. Every Gevi product (purchased via an official or authorized channel) is entitled to a 12-month warranty and lifetime tech support. If you encounter any issue with Gevi ice maker, please feel free to contact us.",
  'images': 'https://m.media-amazon.com/images/I/31CY3buX56L.jpg',
  'rating_number': 148,
  'price': 509.99,
  'average_rating': 4.1,
  'parent_asin': 'B0B4G58R7X'},
 {'description': 'AeroPress Flow Control Filter Cap, No Drip Filter Cap for AeroPress Portable Coffee Press, Specialty Coffee MakerCOMPLETE BREW CONTROL - Attach the AeroPress Flow Control Filter Cap to any AeroPress coffee maker to stop drip through which allows you to extend brew time and use coarser-ground coffee like pre-ground medium. ESPRESSO-STYLE CREMA - When used with a paper filter and dark roast coffee, the AeroPress Flow Control Filter Cap uses a build up of pressure to create an espresso like crema. FILTER FLEXIBILITY - The flexible AeroPress Flow Control Filter Cap can be used with the AeroPress Stainless Steel Reusable Filter or AeroPress Paper Micro-Filters (or even both at once) to create a variety of delicious flavor profiles. (Filters sold separately) FITS ALL AEROPRESS COFFEE MAKERS - Compatible with AeroPress Go and AeroPress Original. Designed in Silicon Valley, Made in USA Patents pending',
  'images': 'https://m.media-amazon.com/images/I/31SJ+46CZbL._AC_.jpg',
  'rating_number': 121,
  'price': 24.95,
  'average_rating': 4.2,
  'parent_asin': 'B0BXCRVZ52'},
 {'description': 'IAHAUCH 12oz/350ml Stainless Steel Milk Frothing Pitcher, Espresso Coffee Cappuccino Latte Art Milk Frother Cup Jug with Decorating Pen, Steaming Pitchers【Professional Milk Frothing Pitcher & Coffee Art Pen】 Make mellow milk froth easily at home. Measure liquids in the kitchen. Perfect for making frothing or steaming milk for cappuccinos, lattes. Come with a coffee art pen to create your own artwork with delicate coffee patterns. 【Precise Graduation & Thoughtful Design】Precise measurements are engraved on the inside of the milk frother cup to measure the right amount of milk you need. The sturdy handle allow you to grab well and focus on your latte art without worrying about injury. 【Dripless Mouth, Perfect Latte Art】 The sharp mouth design of the milk frother pitcher can precisely control the pouring and create coffee art. 12oz/350ml steaming pitchers (3 inches*3.5 inches) is perfect for 1 or 2 cups of lattes or espresso needs. Be your own barista at home/office. 【Superior Quality & Clean Effortlessly】Made of high-grade 304 stainless steel, anti-rust, anti-stain. Clean up effortlessly in seconds and it is dishwasher safe. ❤Enjoy the durability and lifetime warranty of the espresso milk frothing pitcher. 【Quality Assurance & Friendly Customer Service】We aim to make every buyer 100% satisfied. If you have any questions about the milk frother pitcher, please contact us for a satisfactory solution.',
  'images': 'https://m.media-amazon.com/images/I/01RmK+J4pJL._AC_.gif',
  'rating_number': 106,
  'price': nan,
  'average_rating': 4.1,
  'parent_asin': 'B0BQWTRS1V'},
 {'description': "200Pcs Unbleached Percolator Coffee Filters, 3.75In Disposable Coffee Paper Filter, Disc Coffee Filters for Bozeman Percolator (White)FITS ALL PERCOLATOR: The disc coffee filter measures 3.75 inches and fits all percolator around 3.75 inches; the diameter of the center hole is 0.39 inches, which is the standard size in the market; suitable for banquets, parties , restaurants and homes, etc. THE STRONGEST COFFEE FILTER PAPER: The percolator coffee filters easily captures all the tiny impurities, oils and bitterness in the coffee without causing any change in the extraction or flavor of the final product, making the coffee taste better. These disposable coffee filters are the strongest seamless filter paper ever made, and every coffee lover should have it! A SAFE AND HEALTHY DRINK: Everyone loves a good, steaming cup of coffee - unless it has that weird oaky taste. But with our coffee paper filter, you don't have to worry about such things. It's made from medical-grade fiber material that's food-safe and free of harmful BPA. it's also more hygienic because it prevents harmful elements from affecting the taste and quality of your drink. A SOLID INVESTMENT: If you thoroughly enjoy the coffee brewing process, our 200-piece disposable filter paper is a great choice, which costs less time and money than a trip to the coffee shop; you can enjoy great coffee anytime, anywhere, just from the comfort of your home! 100% SATISFACTION PROMISE: We are confident that our coffee filter will win your heart with its high quality medical grade fiber material and fast filtration performance for sure! If you are not satisfied with our coffee filters, please contact us as soon as possible and we will provide product replacement or refund",
  'images': 'https://m.media-amazon.com/images/I/31ceXdplehL._AC_.jpg',
  'rating_number': 117,
  'price': 11.99,
  'average_rating': 4.5,
  'parent_asin': 'B0BGPP5S3R'},
 {'description': 'WANAI Beverage Refrigerator Cooler Mini Fridge Glass Door 125 Cans Beer Fridge Drinks Organizer for Soda Wine Small Refrigerator with 7 Thermostat 3 Shelves LED Lights for Home Bar Office🥇【Practical & Versatile Beverage Cooler】WANAI beer fridge glass door is an ultimate fridge to chill soft drinks, beers, wine, champagne, snacks for family gatherings, freeing up space in your main refrigerator. It is ideal to use anywhere in your apartments, home kitchen, offices, parties, bars, restaurants and so on. 🥇【Powerful Cooling】Our can mini fridge also as a drinks cooler features energy efficient advanced technology, consistent and uniform temperature supply inside. With a super quiet R600a compressor that cool quickly, keeps sound at 40 dB, so you can rest easy and enjoy peace of mind. 🥇【Stylish Design】Black body & special stainless steel exterior --Complete with recessed door handle & 2 layers of tempered glass door, blends beautifully with any home or office decor. Interior soft blue LED light looks amazing(can be turned off) when it lights up, adds atmosphere while keeping drink selection effortless. 🥇【Blue LED & Smart Control】Thanks to mechanical button to adjust temperature, you can simple adjust the temperature from 32℉ to 50℉, and turn the interior LED light on or off. 🥇【WARRANTY SERVICE】Our mini refrigerator3.2 cu.ft have 1-year warranty and 30-day return policy. If there is any problem with the product, customers could contact us first,and we will try to give a 100% satisfied solution.',
  'images': 'https://m.media-amazon.com/images/I/51bY2oo5MhL._AC_.jpg',
  'rating_number': 108,
  'price': 199.99,
  'average_rating': 4.2,
  'parent_asin': 'B0C2PVJMHB'},
 {'description': '2 Pack Fridge Drawer Organizer, Refrigerator Organizer Bins, Pull-out Refrigerator Storage Drawer Bins Box, 12" Length, Refrigerator Pull out Under Shelf Holder Vegetable Veggies Fruit ContainerPlease Note & Measure the fridge shelf before buying : The shelf length range should be 11.8” - 17”, the shelf thickness must be less than 0.6”. It is featured with Extendable Rails Design -The freezer organizer bins design with a smooth spring pull rod. It is adjustable. This fridge drawer is not for slanted or curve downward. 2 Pack, Unique design, 50%+ Space Saving Fridge Organizer Drawer - 2 Pack refrigerator organizer bins feature with hanging & pull-out design, perfect for taking advantage of dead space under the refrigerator plate. Expand the usable space for more than 50% to make your fridge sorted and organizer in order. Transparent, Pull-out with Built-in Handle - Visable clear design makes the fridge storage containers easier to locate and find your items quickly. No need to open the bags and rummage through them one by one. The practical, integrated handles facilitate the removal and flexible movement of the kitchen storage units. 1 Bear Shaped Towel for Easy Maintain, Healthy & Safety - Fridge drawer organizer bins are made of food-grade PET & ABS material, BPA free. Refrigerator drawer organizer bins come with 1 x bear shaped maintain towel. Just untie it, it is a square towel for easy maintain the food storage containers. Dividers Freely for Your Various Needs - Optional insertable dividers are equipped inside the refrigerator storage box. You can divide the fridge drawer into 4 grids, 2 grids or without grids. Fridge organizer drawer is great for your daily storage needs, especially for small things. Making our refrigerator storage tidier. Portable & Stackable for Small things - You can using the refrigerator bins stacked or side-by-side. Help for maximize your fridge or kitchen space, make organizing and everyday living a little easier. This organizer bin for the fridge is ideal for fruits, meat, milk, salad dressing, drink bottles, canned food, and packaged food, condiments, jelly, and more. Say Goodbye to the Chaotic - Package included: 2 x fridge organizer bins, 4 drawer dividers & 1 bear shaped maintain towel. With these organizer bins, your refrigerator, kitchen cabinet, pantry, bedroom, bathroom will be more neatly.',
  'images': 'https://m.media-amazon.com/images/I/51Mx3P--hwL._AC_.jpg',
  'rating_number': 183,
  'price': 27.87,
  'average_rating': 4.3,
  'parent_asin': 'B0C4PSMDZD'},
 {'description': "Reusable Vertuo Pods(5Pcs), Refillable Coffee Capsule for Vertuoline & Vertuo Pod, 230 mL Coffee Pods Compatible with Nespresso Vertuo Coffee Machine, with 2 Pcs Reusable Silicone Lids, Scoop, Brush☕【 Enjoy the coffee 】- The package contains 5 x 230ml reusable vertuo pods, 2 x reusable silicone vertuo pods lids, 1 x scoop, 1 x brush; just fill the pods with your favorite finely ground coffee powder, feed into the coffee machine, wait a little and you're ready for a delicious cup of coffee! It's that easy! ☕【Reassured raw materials 】- Our Vertuo pods are made of food-grade PP material, BPA-free, no harmful substances, environmentally friendly and odorless; you can put the coffee powder in with confidence that it will not leak out. ☕【 Perfect compatibility 】- Our Coffee Capsule compatible with Delonghi ENV135, Delonghi ENV150, Nespresso Vertuoline Plus, Nespresso Vertuoline GCA1. ☕【 DIY, environmental protection, saving money 】-With this reusable coffee capsule, you no longer need to repurchase capsules! You can mix and match your favorite coffee powder and brew your own cup of flavor! After use, you can clean it and continue to use it. The capsules and lids are also recyclable. Yes, we put our heart and soul into making the ultimate coffee experience for every customer! ☕【 100% customer satisfaction 】- Customer is God, your trust and support is our greatest motivation! If You have any questions about the capsule, please contact us, we will reply to you within 24 hours.",
  'images': 'https://m.media-amazon.com/images/I/51d0SuSIelL._AC_.jpg',
  'rating_number': 199,
  'price': 20.99,
  'average_rating': 3.2,
  'parent_asin': 'B0BL7QM9HC'},
 {'description': "Refrigerator Drip Catcher Tray: Cuttable Refrigerator Drip Tray for Fridge Water Dispenser, Absorbent Drip Tray, Refrigerator Accessories for Whirlpool, GE, Samsung (4PCS, Black) (Semi-Circular)Make Fridge Tray Neat and Free Your Hands: Are you tired from wiping the water stain on the fridge drip tray? The refrigerator drip pan can help you catch the drips or spills effectively from water dispenser. Water stains will not gather on the fridge tray and don't need to wipe it out anymore. Anti-slip Design: The bottom of refrigerator drip trays is designed with anti-slip rubber, so the fridge water catcher mat can stay in place when opening or closing the fridge door. Cut to Fit: The size of refrigerator drip catcher is 8.3 x 3.7 inches which can fit most refrigerator water trays. If the size is unsuitable, you can use scissors to cut the drip catcher tray to fit your refrigerator. Super Absorbent & Dry Quickly: The upper layer of the pad is the absorbent leather, and the middle is diatomite ingredients material which can absorb more drips and dry quickly. This fridge drip catcher can also be a good decoration for your refrigerator and look more modern than other materials. Care Instruction: If refrigerator ice dispenser mat can not absorb more water, please replace and do the wash for it. You can wipe it by a towel or rinse it, hang to air-dry, but do not twist or contort it to dry because of its leather and diatomite materials.",
  'images': 'https://m.media-amazon.com/images/I/41h16MwhkZL._AC_.jpg',
  'rating_number': 353,
  'price': 14.99,
  'average_rating': 4.5,
  'parent_asin': 'B0BGNFZ122'},
 {'description': 'Kismile Nugget Ice Maker Countertop,Portable Compact Ice Maker Machine with Self-Cleaning Function,44Lbs/24H,for Home/Kitchen/Office/Bar',
  'images': 'https://m.media-amazon.com/images/I/41GsUX2A5SL.jpg',
  'rating_number': 639,
  'price': nan,
  'average_rating': 3.9,
  'parent_asin': 'B09PQL8XLS'},
 {'description': "Durabasics 6 Pack of Premium Humidifier Filters Compatible with Honeywell Humidifier Filter HAC-504, HAC-504AW & Honeywell Filter A | Replacement for Honeywell Filter HCM 350 & Cool Mist Humidifiers6 Piece Value Pack - 6 filters compatible with Honeywell replacement wicking Filter A for your Honeywell HAC-504, HAC-504AW, and HAC-504V1 humidifier filters. Made from high-quality, durable material with an optimized filter design to maximize your compatible Honeywell HCM 350 filter moisture output Upgraded Blue Filters - Our upgraded filters compatible with Honeywell HCM350W filter feature a blue pre-filter to catch large particles before they enter your air, for even higher air quality Rigid Construction To Reduce Sagging - Our replacements for Honeywell humidifiers filter, Honeywell humidifiers filters and Honeywell cool humidifier filter are constructed with rigid absorbent paper to improve our filter's structure once wet and reduce sagging Compatible With Honeywell Humidifier Filter Model HCM350W & More - Fits HCM350W, HCM-350, HCM350, HCM-350B, HCM350B, HCM-350W, HCM-350B-CST, HCM-300, HCM300, HCM-300T, HCM300T, HCM-305T, HCM305T, HCM-310T, HCM310T, HCM-315T, HCM315T, HCM305BCST, HCM-450B-CST, HCM450BCST, HCM-500, HCM500, HCM-530, HCM530, HCM-535, HCM353, HCM-535-20, HCM53520, HCM-540, HCM540, HCM-550, HCM550, HCM-550-19, HCM55019, HCM-551, HCM551, HCM-560, HCM560, HCM-600, HCM600, HCM-630, HCM630, HCM-631, HCM631 Usage Tips - For best results, flip your compatible Honeywell humidifier filter HAC 504 replacement daily and only fill humidifier tank with distilled water. Hard water degrades ALL compatible Honeywell humidifier filters and yellows them prematurely. Soak in cool water before replacing to ensure uninterrupted moisture output.",
  'images': 'https://m.media-amazon.com/images/I/51fIWYNgyfL._AC_.jpg',
  'rating_number': 4367,
  'price': 32.99,
  'average_rating': 4.5,
  'parent_asin': 'B0B8M4H11G'},
 {'description': "Stainless Steel Stove Gap Cover, 2 Pack, Heat Resistant and Durable, Fit for Gap Between Stovetop and Counter, Used for Prevent Messy Spills and Debris, Easy to Install, Adjustable 17-25 inch LengthCONFORM TO THE GAP, STAY IN PLACE: Suitable for gaps between the stove and the counter with a width of under 1.5 inches and a height difference of less than 1 inch. Adjustable length of 17-25 inches. They are designed to fit seamlessly without the need for cutting. Our unique design features dual-side retractable and spring mechanisms, ensuring a secure and snug fit. PREVENTS SPILLS AND CRUMBS: The gap cover helps prevent food particles, crumbs, and other debris from falling into the gap between the stove and counter, keeping the kitchen cleaner and easier to maintain. HEAT RESISTANT: Prioritize your well-being with our top-notch, premium-grade Stainless Steel coated material. Our counter gap covers are designed to endure extreme heat up to 446℉, ensuring no melting and maintaining their structural integrity. Rejoice in the peace of mind that comes with using a safe and reliable product. AESTHETICALLY PLEASING: Stainless steel construction enhances the aesthetic appeal, contrasting with silicone alternatives. Matches well with black stovetops for a seamless transition from stove to countertop, improving the kitchen's overall look. The stainless steel gap cover offers a solution for the unsightly gap between the stove and countertop, making cleaning a breeze and keeping your kitchen hygienic. Say goodbye to the hassle and frustration of traditional gap covers and upgrade to a product that is built to last. Order your stainless steel gap cover today and experience the difference for yourself!",
  'images': 'https://m.media-amazon.com/images/I/215uQNiatxL._AC_.jpg',
  'rating_number': 132,
  'price': 10.95,
  'average_rating': 3.9,
  'parent_asin': 'B0BMVSJ1KL'},
 {'description': "Refrigerator Drip Tray,Cuttable Fast Absorbent Drip Tray, Refrigerator Drip Catcher Hide Stain,Mini Fridge Drip Tray For Refrigerator Water Dispenser,Quick Dry Water Drip Pads(4Pcs,Grey,Semi-Circular)【Super Absorption】This refrigerator drip tray have super absorbent soft diatomite that can suck up spilled water or coffee instantly. Mini fridge drip tray strong water absorption, durable and reusable.Make you no need to wipe the sink fridge tray every time after using cuttable refrigerator drip catcher. 【Hide Stains】The drip pad made of special PU leather surfaces hide coffee stains, water residue,milk stains, and any other dark messy stains. refrigerator drip catcher no need to clean frequently because hide stains well. Always keep the water catcher clean and tidy,avoid the trouble of cleaning the fidge drip trays. 【Anti-slip】The rubber backing bottom of the refrigerator drip mat for countertops has a good anti-slip effect. It's non-slip, waterproof and heat-proof. the anti-slip bottom will be absorbed on the water catcher to prevent it from moving when you open the refrigerator. The waterproof bottom can prevent spilled liquid from damaging the clean look to your refrigerator. 【Cut to Fit】 Fits Most Fridge Drip Trays - Between the Semi-circular and Rectangular design, the Drip Pad is sized to fit a wide variety of drip trays.If the size is unsuitable,cut the drip catcher tray to fit your refrigerator.If it cannot cover your long length of drip tray adequately, you can trim each drip guard with scissors and then piece them together. 【Easy Clean】Drip catcher no need to clean frequently because hide stains well. Only wash it every two weeks or long time. This refrigerator accessories will not fade or wrinkle. Drip tray for mini fridge can be washed by hand, dry naturally.",
  'images': 'https://m.media-amazon.com/images/I/31l2vDyVcYL._AC_.jpg',
  'rating_number': 201,
  'price': 13.99,
  'average_rating': 4.2,
  'parent_asin': 'B0BTMMP926'},

In [98]:
co = cohere.ClientV2(api_key=os.getenv("COHERE_API_KEY"))
text_inputs = [
    {
        "content": [
            {"type": "text", "text": "hello"},
            {"type": "text", "text": "goodbye"}
        ]
    },
]
response = co.embed(
    inputs=text_inputs,
    model="embed-v4.0",
    input_type="classification",
    output_dimension=1536,
    embedding_types=["float"],
)
print(response)
print(response.embeddings )
print(response.embeddings.float[0])

response_type='embeddings_by_type' id='edc7ced4-2f84-4aea-a969-ec2e76a5deaa' embeddings=EmbedByTypeResponseEmbeddings(float_=[[0.026357077, -0.042990185, 0.0069411234, -0.0057256278, 0.018296419, 0.002319039, -0.035825156, 0.02712476, -0.033522107, 0.010875493, -0.0079646995, 0.05629667, -0.047084488, -0.048108064, 0.009915891, 0.011323308, -0.0078047663, 0.041710712, -0.00067172165, -0.03301032, -0.025717342, 0.023670191, 0.0029747672, -0.036592837, -0.021239199, -0.0034225818, 0.021878934, 0.0058215875, 0.033266213, -0.024309926, -0.033522107, 0.01394622, 0.009212183, 0.014969796, -0.024949662, 0.0054377466, -0.01740079, -0.01631324, 0.040175352, 0.015289664, -0.009084236, 0.008028673, 0.0039183763, -0.0047660246, 0.022646615, 0.026996814, 0.010747546, -0.016889, -0.0011195361, -0.0074209245, -0.0012954632, 0.016761053, -0.013690327, 0.0020791383, 0.03863999, 0.0007037084, 0.022262774, 0.05680846, -0.0055656936, -0.0012554798, -0.012986618, 0.019703835, -0.013882247, -0.0017832611, 0.0019272014, 0.029939592, -0.051946472, 0.04068714, 0.023542244, 0.0032946346, 0.018168472, -0.012538805, -0.035313368, 0.040943034, 0.038384095, -0.0087643685, 0.0043821842, -0.029939592, -0.021367146, 0.011771122, 0.011323308, 0.037872303, 0.03262648, -0.022646615, 0.033266213, 0.002446986, -0.012602777, -0.029555753, -0.018296419, -0.029555753, -0.022134827, -0.032370586, -0.02674092, -0.0972397, 0.026868867, 0.04068714, 0.012730724, 0.019575888, 0.030579329, -0.017528737, -0.0039023831, -0.035825156, 0.051946472, 0.003486555, -0.022774564, 0.020599464, -0.0721621, 0.012858671, -0.008892315, 0.0009516057, 0.040431246, -0.018040525, -0.020471517, -0.07523282, 0.0006397349, -0.024309926, 0.018552313, 0.0027668534, -0.021111252, 0.013306486, -0.0054377466, -0.007996687, -0.048363958, -0.02072741, -0.015481586, -0.029171912, 0.007740793, 0.026612973, -0.044781443, -0.050667003, 0.0035345354, 0.018168472, 0.035057474, -0.007548872, -0.0065892693, -0.03608105, 0.0065572825, -0.0039823498, 0.033266213, 0.000103956925, -0.0046700644, 0.023542244, 0.038895883, 0.0010875494, -0.032114692, -0.0057256278, -0.0064293356, -0.022518668, 0.009851918, -0.011643175, -0.011387282, 0.04861985, 0.01740079, 0.012154963, -0.024565822, 0.039151777, 0.03301032, 0.019192047, 0.027252708, -0.052714154, 0.06243813, 0.010171785, 0.044781443, 0.041198928, -0.012666751, -0.021239199, -0.022262774, 0.0040943036, -0.033522107, 0.012730724, -0.0025909264, 0.03608105, -0.027764494, -0.004510131, 0.011195361, -0.031219065, -0.0117071485, 0.0017432775, -0.010939467, -0.013498407, -0.008636421, -0.021239199, 0.023926085, 0.013434433, -0.017272841, -0.024181979, -0.00786874, -0.023926085, -0.04452555, -0.017912578, 0.012922645, 0.04068714, 0.016249267, 0.01100344, 0.016377214, 0.011579202, -0.042222504, -0.024054032, -0.03301032, -0.013114565, 0.014010194, 0.031986747, -0.012922645, -0.0053097997, 0.006205429, -0.039663564, 0.0078047663, -0.047340382, 0.0032306612, -0.02507761, 0.002111125, 0.005693641, 0.0048619853, -0.04145482, -0.008508474, -0.0076768184, -0.007772779, -0.029299859, 0.00412629, 0.0003018749, 0.00422225, -0.019447941, -0.022262774, 0.06294992, -0.00540576, -0.027636547, -0.0027188733, -0.05169058, -0.022646615, 0.01778463, -0.024054032, 0.013626354, -0.0014074168, 0.008380527, -0.0067172167, 0.007900726, 0.047084488, 0.0040463232, 0.0025109595, 0.0009995858, -0.019064099, 0.019319994, -0.016889, -0.022646615, 0.033522107, -0.003006754, 0.0037584426, 0.026357077, -0.05169058, 0.026612973, 0.049387537, -0.01631324, -0.01503377, -0.005981521, -0.005245826, -0.008828342, 0.033778, -0.01394622, 0.0465727, -0.0010235759, 0.03761641, -0.0003878393, -0.034033895, 0.002574933, -0.020855356, 0.010427678, -0.0022550656, -0.021111252, -0.019575888, -0.029939592, 0.0029747672, 0.015865427, 0.040431246, 0.033778, 0.018040525, -0.0007516885, 0.0016793042, 0.03301032, 0.012154963, -0.0027188733, -0.038128197, -0.02622913, -0.014905822, 0.020855356, -0.015673505, -0.0039183763, 0.006397349, 0.0020951317, -0.035057474, -0.02674092, -0.006109468, -0.009020262, 0.0039023831, -0.012538805, 0.003390595, 0.002063145, -0.0015913405, -0.033522107, 0.007165031, -0.016633106, 0.0071330443, 0.026101183, 0.04964343, 0.005757614, 0.0031027144, -0.0068451636, 0.033266213, 0.00815662, -0.027380655, -0.021239199, 0.030195488, -0.015929399, -0.009468076, -0.0010635592, -0.008572447, 0.03761641, -0.03684873, 0.028020388, -0.009659997, 0.008316553, 0.009851918, -0.038384095, 0.040175352, 0.00407831, -0.028532177, 0.0004997929, -0.014330062, 0.031730853, 0.002367019, -0.040943034, -0.013306486, -0.010939467, -0.034033895, 0.0031986744, -0.024821715, -0.008956289, -0.0014234103, -0.00697311, 0.023926085, 0.031602904, 0.009148209, -0.015865427, 0.03275443, -0.0043182103, -0.011067414, -0.0028468205, 0.0023030457, -0.014777876, 0.031091116, -0.04196661, -0.013498407, -0.041198928, 0.016633106, -0.03480158, -0.029555753, 0.005757614, -0.012602777, 0.014777876, -0.049131643, -0.0033106282, 0.070626736, -0.026868867, -0.040431246, -0.04068714, 0.026868867, 0.023414297, -0.03301032, 0.050922897, -0.005789601, -0.036336944, -0.00403033, 0.011067414, 0.0069091367, -0.017528737, -0.05680846, 0.010299732, 0.036336944, -0.02034357, 0.015993373, 0.029427806, 0.005693641, -0.024437873, -0.010939467, 0.0004338202, 0.0145219825, 0.020087676, 0.0084445, -0.011643175, -0.12027016, 0.009468076, -0.0011275328, 0.028276283, 0.021367146, -0.047596276, 0.024054032, -0.044269655, -0.009915891, 0.02328635, 0.053737734, 0.019575888, 0.01740079, -0.013114565, 0.019192047, 0.012218936, 0.047340382, -0.038128197, -0.046316806, -0.03556926, -0.001199503, 0.037104625, 0.021878934, -0.024949662, -0.0044781445, -0.005533707, 0.0033586083, 0.029427806, 0.03275443, -0.024054032, -0.014777876, -0.008892315, 0.0073569515, -0.024309926, 0.00036384922, 0.021239199, -0.024693768, -0.033778, -0.016057346, -0.01573748, 0.003486555, 0.0275086, -0.061926343, 0.01778463, -0.02584529, -0.034033895, -0.0049579456, 0.042478397, -0.0043182103, -0.00085564546, 0.010427678, -0.011643175, -0.034033895, 0.02034357, -0.049899325, 0.029683698, -0.03428979, 0.026868867, 0.021878934, 0.011195361, 0.024181979, -0.0025429463, 0.009084236, 0.005693641, -0.00786874, -0.010747546, 0.047596276, 0.057064354, 0.0070370836, 0.0013914234, -0.018040525, 0.0006277399, 0.022518668, 0.013306486, -0.00069171336, 0.01740079, -0.02162304, -0.010619599, 0.0550172, -0.036336944, 0.024181979, 0.0013194532, 0.04196661, 0.04529323, 0.00014294077, -0.10542831, 0.0059495345, 0.028916018, -0.01394622, -0.018552313, 0.014969796, -0.031730853, 0.017528737, 0.018680258, 0.01612132, 0.04964343, 0.020471517, -0.022518668, -0.0039023831, -0.038895883, -0.035825156, 0.013306486, -0.033778, -0.0076128454, -0.024821715, 0.04964343, 0.047340382, 0.0074209245, -0.0059495345, 0.008572447, -0.0053417864, -0.014777876, -0.052202366, -0.0146499295, 0.0084445, -0.02584529, 0.029299859, -0.012282911, 0.003486555, 0.0064613223, 0.046828594, -0.010491652, 0.025973236, 0.04529323, 0.0049579456, -0.0023830123, 0.01650516, 0.02712476, 0.0041902633, 0.010939467, 0.018936152, 0.005213839, 0.029683698, -0.035313368, 0.031219065, -0.019192047, -0.014841849, 0.041710712, 0.0032946346, -0.024054032, 0.02622913, 0.004254237, -0.007772779, -0.022902511, -0.002622913, 0.012602777, -0.03608105, 0.014330062, 0.0054377466, -0.050922897, 0.00011995029, 0.013306486, 0.03262648, 0.039663564, -0.011387282, 0.015673505, 0.13101771, 0.0013434433, -0.006365362, -0.034033895, -0.02507761, 0.015097744, 0.035313368, -0.0043182103, 0.0015513572, 0.018168472, 0.0076768184, 0.01740079, -0.005981521, 0.014266089, 0.019064099, 0.12897056, -0.00550172, -0.0039183763, -0.0021591051, -0.0039023831, 0.0015913405, -0.03761641, -0.0050858925, -0.016761053, 0.026357077, 0.0028468205, -0.007197018, 0.0026868866, 0.022134827, 0.040943034, 0.013818273, 0.049131643, 0.019192047, 0.007452911, -0.02200688, 0.058599718, 0.03275443, 0.009851918, 0.02584529, -0.013306486, 0.019319994, -0.02622913, 0.022390721, -0.004414171, -0.0021750988, 0.012474831, -0.007484898, 0.028020388, 0.022134827, 0.014394036, 0.0004238244, 0.06064687, 0.008380527, -0.015993373, 0.03940767, -0.039663564, 0.055273093, -0.02840423, -0.04554913, 0.004638078, -0.014585956, -0.02789244, 0.022646615, -0.07983892, 0.029299859, 0.013626354, 0.03301032, 0.018040525, 0.061414547, -0.025205554, 0.00023390306, -0.0049579456, -0.037360515, -0.020599464, 0.019831782, 0.006493309, -0.008636421, 0.014138142, -0.0063333753, 0.033778, -0.02072741, -0.028916018, -0.017528737, 0.014394036, 0.009148209, 0.009596024, -0.041198928, -0.007836753, 0.009084236, 0.018552313, 0.0036784757, -0.02072741, 0.03006754, -0.005021919, -0.019192047, 0.020471517, 0.002367019, 0.0067172167, 0.010363705, -0.020983305, 0.03480158, -0.001503377, -0.02584529, 0.030579329, 0.0079646995, 0.048363958, 0.00137543, 0.041198928, -0.031986747, 0.0023510256, -0.022774564, 0.013690327, 0.014074167, 0.011131387, -0.00815662, -0.003742449, -0.061670445, 0.023926085, -0.00035985088, -0.019575888, 0.010427678, 0.018936152, 0.012922645, -0.03480158, -0.016249267, -0.004893972, 0.044269655, 0.017272841, 0.01503377, 0.005277813, -0.0114512555, 0.014202115, -0.01356238, 0.04196661, 0.0021591051, 0.00825258, 0.021111252, -0.014841849, 0.013050592, 0.014138142, 0.00026189146, 0.02674092, 0.0014074168, -0.009340129, -0.03262648, 0.02200688, 0.0032946346, 0.016249267, -0.02712476, -0.015353637, -0.031091116, 0.022390721, 0.0072609913, -0.0072609913, -0.0026868866, -0.005757614, -0.07574461, 0.029683698, 0.008892315, 0.007996687, 0.019447941, 0.007900726, 0.035313368, 0.02072741, 0.021750987, 0.020215623, 0.009148209, -0.03147496, -0.030579329, -0.007452911, 0.013242513, -0.022774564, -0.017016947, 0.03608105, -0.007996687, -0.026485026, 0.029043965, 0.016761053, 0.04401376, 0.020983305, -0.018424366, -0.0037904293, -0.041710712, -0.00055976806, 0.004702051, 0.0117071485, 0.010299732, 0.0027188733, 0.025589395, -0.030835222, -0.022518668, -0.035057474, 0.012346884, 0.027636547, 0.018296419, 0.02712476, 0.011195361, -0.015289664, -0.024565822, -0.01740079, 0.060902763, -0.027764494, 0.0063013886, -0.008956289, -0.014969796, -0.032114692, 0.003598509, -0.013434433, 0.001887218, -0.025717342, -0.0016073339, 0.03991946, 0.022390721, -0.024181979, 0.00024489852, 0.013690327, 0.009148209, -0.00018692254, 0.0075808587, 0.018680258, 0.027636547, 0.026868867, 0.02712476, 0.007772779, 0.003950363, -0.018680258, 0.010939467, -0.002111125, -0.028148334, 0.0027348667, -0.05424952, 0.029427806, 0.005053906, -0.040943034, 0.002063145, -0.047084488, 0.03006754, -0.01356238, 0.016633106, 0.027764494, -0.02072741, -0.0034065885, 0.009340129, -0.036592837, 0.021111252, -0.037872303, 0.0024309927, -0.042478397, 0.028916018, -0.024437873, -0.027764494, -0.013434433, -0.008636421, -0.00043182104, 0.05117879, -0.0012154963, -0.007292978, 0.029939592, 0.020599464, -0.005373773, -0.035825156, 0.01356238, 0.006397349, -0.028532177, 0.0007876736, 0.00678119, 0.006173442, 0.027636547, 0.0049899323, -0.018040525, 0.06064687, -0.03134701, 0.06448528, -0.0060774814, -0.03428979, 0.024309926, 0.0034705617, -0.012730724, -0.020471517, -0.017272841, 0.0037264556, -0.00550172, -0.049899325, 0.007996687, -0.0068451636, -0.05476131, 0.01740079, -0.00678119, -0.0007996686, 0.0009915892, 0.014585956, 0.022774564, -0.024821715, -0.018296419, -0.018424366, -0.03301032, -0.027380655, -0.010939467, 0.012218936, 0.020215623, 0.022134827, 0.011195361, -0.007548872, 0.0043501975, -0.014010194, 0.02622913, -0.013882247, 0.029171912, 0.010747546, -0.00035985088, 0.03224264, -0.04145482, 0.012730724, -0.020599464, -0.020983305, -0.0058535743, -0.01337046, 0.055528987, 0.0006477316, -0.00014194119, -0.03301032, -0.014841849, -0.023030456, 0.0012554798, -0.024565822, 0.021878934, 0.008828342, 0.025205554, 0.07113852, -0.005757614, -0.030323435, -0.01081152, -0.01995973, 0.02200688, 0.038384095, -0.025205554, -0.021495093, 0.022262774, -0.0117071485, -0.0019351982, -0.015353637, 0.03224264, 0.10235758, -0.019192047, -0.0025109595, 0.018296419, -0.02507761, 0.030323435, -0.04554913, -0.03224264, 0.028660124, 0.005021919, 0.02034357, -0.0032306612, -0.008508474, -0.047084488, 0.043501973, 0.024821715, 0.008316553, 0.01573748, 0.03275443, -0.014713903, 0.015929399, -0.042478397, -0.011899069, 0.01650516, 0.00697311, 0.0030387407, 0.0017752644, -0.0007596852, 0.0016873009, -0.05476131, 0.034033895, -0.002039155, 0.012602777, -0.017528737, -0.041198928, 0.005373773, -0.014266089, -0.021750987, -0.014010194, 0.070626736, -0.0026548998, 0.023926085, -0.0059175477, 0.014010194, 0.028916018, -0.015225691, -0.024565822, -0.022262774, -0.00825258, -0.0071330443, -0.012282911, 0.01503377, -0.014074167, -0.0033746017, 0.004893972, 0.050922897, -0.038128197, -0.009276156, -0.014138142, 0.014585956, 0.0050858925, 0.016761053, -0.028276283, 0.023926085, 0.0008956289, 0.036592837, -0.00697311, -0.0087643685, -0.052202366, 0.033778, 0.09775149, 0.015801452, -0.012794698, -0.016761053, 0.038895883, -0.0029587739, -0.0080926465, 0.017912578, 0.004542118, -0.019575888, -0.007516885, 0.0028468205, -0.02622913, -0.0073569515, 0.057832036, -0.042990185, -0.02712476, 0.0043821842, -0.02674092, 0.05732025, -0.0721621, -0.017272841, 0.015225691, 0.00036784756, -0.0035825155, -0.0048299986, 0.0465727, -0.021111252, 0.00422225, 0.028020388, 0.007644832, 0.012986618, 0.0063333753, -0.029555753, -0.0037584426, -0.004638078, 0.014010194, -0.014394036, -0.026485026, 0.05041111, -0.016249267, -0.02162304, 0.019575888, 0.0055976803, -0.030451382, 0.0114512555, -0.016761053, 0.008380527, 0.009084236, -0.015161717, -0.049899325, 0.0033586083, -0.042222504, 0.014266089, 0.011067414, -0.014138142, 0.0044461577, 0.014394036, -0.028148334, 0.028276283, 0.04785217, -0.01573748, 0.02328635, 0.0025109595, -0.000687715, 0.0013354466, -0.008572447, 0.0117071485, 0.03147496, -0.0054697334, 0.016761053, 0.03275443, -0.019064099, 0.0051178792, 0.0025109595, 0.012986618, 0.005661654, -0.01740079, 0.015609533, -0.038128197, -0.0046700644, -0.03275443, -0.0024949661, -0.022134827, -0.014394036, 0.015865427, -0.023414297, -0.012666751, 0.019064099, -0.012474831, 3.52354e-05, 0.002622913, 0.049131643, -0.00090362557, 0.035825156, -0.0024309927, -0.018680258, -0.046828594, 0.030195488, -0.0025109595, -0.02712476, -0.034033895, 0.050922897, -0.010875493, -0.0034545683, -0.013242513, -0.052202366, -0.03428979, 0.029171912, -0.061670445, 0.014266089, -0.0016713075, 0.003646489, -0.030835222, -0.026357077, -0.004542118, -0.011259334, -0.07267389, -0.018808205, -0.023926085, 0.020471517, 0.010299732, 0.015417611, 0.01740079, 0.0079646995, -0.014841849, -0.0021271184, -0.0137543, -0.0019991717, -0.008700395, 0.0005437747, -0.032114692, -0.012282911, 0.045805022, -0.026996814, -0.004925959, -0.00687715, -0.061414547, 0.0008996272, -0.0034225818, -0.0063333753, -0.0058535743, 0.063717596, 0.01740079, -0.031602904, 0.0040943036, 0.018424366, 0.022902511, -0.034033895, 0.025461448, -0.03863999, 0.063717596, 0.035825156, 0.0031187078, -0.002446986, 0.009787944, -0.004062317, -0.01740079, -0.02200688, 0.022390721, -0.0015833438, -0.008956289, 0.004510131, 0.012794698, -0.016377214, -0.01778463, -0.0087643685, -0.033778, -0.013882247, 0.01740079, -0.006365362, -0.073185675, -0.0020951317, 0.008956289, -0.046060912, 0.0076128454, -0.007452911, -0.012986618, -0.024181979, -0.05732025, -0.011323308, -0.02162304, -0.021111252, 0.0040143365, 0.007484898, -0.016057346, 0.027380655, 0.0012874665, 0.0117071485, 0.020215623, -0.048108064, 0.022134827, 0.03480158, 0.0058215875, 0.014713903, 0.05015522, -0.013050592, 0.00697311, 0.040175352, 0.0031666877, 0.01650516, -0.019831782, -0.036592837, 0.006205429, -0.051434685, 0.023926085, 0.019831782, 0.0021910921, 0.0067492034, -0.016761053, 0.0046700644, 0.02674092, 0.0045741047, 0.0087643685, 0.022390721, 0.016633106, 0.009148209, 0.019831782, 0.008700395, 0.011131387, -0.028788071, 0.011067414, 0.021878934, -0.017528737, -0.022134827, -0.018680258, 0.0024949661, 0.019064099, -0.016633106, -0.007644832, -0.0026708932, 0.0014474002, -0.04529323, -0.029427806, 0.008188607, 0.01573748, 0.014202115, 0.009723971, 0.023798138, 0.011195361, 0.0064613223, -0.020855356, -0.02674092, -0.033778, 0.015801452, 0.0019991717, 0.016761053, 0.014905822, -0.028276283, -0.012410858, 0.0114512555, -0.0073569515, -0.03684873, -0.023926085, 0.0023510256, 0.03301032, -0.07727998, -0.00668523, -0.01573748, -0.0063013886, 0.025333501, 0.009020262, -0.023926085, 0.006813177, -0.016377214, 0.0048299986, 0.012410858, -0.016889, -0.034545682, -0.018552313, 0.02584529, 0.035313368, 0.035057474, -0.027764494, -0.0048299986, -0.004702051, 0.02328635, 0.0021271184, 0.0275086, 0.020215623, 0.0145219825, -0.013306486, 0.01995973, -0.002878807, -0.00045181278, 0.0033586083, 0.0059175477, -0.03608105, -0.0051178792, 0.008188607, -0.05297005, -0.0063013886, 0.06013508, 0.036592837, 0.015097744, 0.017144894, 0.018040525, -0.01573748, -0.013690327, -0.05629667, -0.030579329, 0.0114512555, -0.017016947, 0.004734038, 0.043757867, -0.015097744, -0.024054032, -0.009532049, -0.02840423, -0.007836753, 0.0117071485, 0.03006754, -0.033266213, 0.033522107, 0.0007117051, 0.0048299986, -0.008572447, -0.028148334, -0.024565822, -0.0059175477, -0.0057256278, -0.04145482, -0.01650516, -0.009979865, 0.007197018, -0.0038703964, 0.014394036, 0.058343824, 0.007836753, 0.023670191, 0.007996687, -0.024437873, 0.066532426, -0.022902511, -0.028660124, -0.004542118, -0.003486555, 0.021367146, 8.5464584e-05, -0.01650516, 0.02162304, 0.010939467, 0.026868867, 0.023670191, 0.004798012, -0.017016947, -0.011579202, 0.00697311, 0.01631324, 0.028276283, 0.0069091367, -0.011963042, 0.009787944, 0.004798012, -0.02034357, 0.014202115, 0.026357077, 0.012666751, 0.008316553, -0.013242513, 0.011259334, -0.025589395, 0.019575888, -0.035057474, -0.019703835, -0.03275443, 0.039663564, -0.0007356951, -0.053737734, -0.0059495345, -0.028532177, 0.03428979, 0.0031347012, 0.011323308, -0.026612973, 0.022134827, 0.010299732, -0.0006117465, -0.0049899323, -0.028020388, 0.010491652, 0.019703835, 0.011195361, -0.00085964374, 0.03428979, -0.0013594367, 0.010939467, -0.02200688, 0.017144894, -0.008956289, 0.02072741, 0.014969796, 0.03684873, 0.0006397349, 0.0146499295, -0.01650516, 0.019575888, 0.0041582766, -0.0015433605, 0.0049579456, 0.018552313, 0.034033895, 0.028532177, -0.009148209, -0.020599464, 0.018936152, 0.0062374156, -0.033266213, -0.020215623, -0.0015993372, -0.03480158, 0.07165031, 0.0275086, -0.009979865, 0.014585956, 0.009212183, 0.026868867, -0.00080366695, 0.004734038, 0.02072741, -0.009979865, -0.030963171, -0.004638078, -0.020471517, -0.0137543, 0.014841849, -0.026485026, -0.013306486, -0.021111252, -0.04554913, -0.045805022, 0.025461448, -0.007292978, 0.007836753, 0.022134827, -0.018168472, -0.014458009, -0.037872303, 0.008828342, 0.05885561, -0.0084445, 0.00036384922, -0.044269655, 0.01650516, -0.051434685, 0.012154963, -0.009212183, 0.0051178792, 0.00046580695, 0.025589395, 0.03224264, 0.00678119, -0.0062374156, -0.010555626, 0.0087643685, -0.0022870523, -0.031602904, -0.015097744, -0.0016473173, 0.073185675, -0.017656684, 0.02584529, 0.02200688, -0.0021431118, 0.007548872, -0.010107812, 0.037360515, 0.0032466545, 0.02840423, -0.014969796, -0.012474831, -0.0145219825, 0.022902511, 0.019831782, -0.03480158, 0.05015522, 0.03940767, -0.0069411234, 0.0075808587, -0.020855356, 0.033522107, -0.032498535, -0.01612132, 0.009915891, 0.020215623, 0.027380655, -0.008572447, -0.0010875494, 0.00060774817, 0.025461448, 0.008028673, 0.015865427, 0.03480158, 0.014841849, 0.029043965, -0.026868867, -0.0059495345, 0.035313368, 0.00036984673, 0.04324608, 0.02072741, -0.009276156, 0.042478397, 0.03428979, 0.01356238, -0.059111506, -0.015545558, 0.02584529, 0.009212183, -0.003390595, -0.0021271184, 0.005373773, -0.0072609913, 0.011771122, 0.015097744, -0.022646615, 0.014969796, 0.01

In [99]:
def generate_embedding(text):
    response = co.embed(
        model="embed-v4.0",
        inputs=[
            {
                "content": [
                    {
                        "type": "text",
                        "text": text
                    }
                ]
            }
        ],
        input_type="classification",
        output_dimension=1536,
        embedding_types=["float"],
    )

    return response.embeddings.float[0]

In [100]:
qdrant_client = QdrantClient(url="http://localhost:6333")

g:\agentic-engineering\ai-engineering\.venv\Lib\site-packages\qdrant_client\qdrant_remote.py:282: UserWarning: Qdrant client version 1.18.0 is incompatible with server version 1.13.6. Major versions should match and minor version difference must not exceed 1. Set check_compatibility=False to skip version check.
  show_warning(

In [101]:
qdrant_client.create_collection(
    collection_name="Amazon-items-collection-01",
    vectors_config=VectorParams(size=1536,distance=Distance.COSINE)
)

True

Embed data

In [91]:
pointStruct = PointStruct(
    id=0,
    vector=generate_embedding("Test text"),
    payload={
        "text":"test text",
        "model":"embed-v4.0"
    }
)

In [92]:
pointStruct

PointStruct(id=0, vector=[0.007233407, -0.0027256315, 0.0061501428, -0.015934462, -0.00020747997, -0.021106172, -0.06038322, 0.03913727, -0.03158937, -0.005346431, -0.0077226227, 0.035363324, -0.020407291, -0.025858555, -0.006744191, 0.0021490557, 0.015165693, 0.012579838, 0.0033895674, -0.025159676, 0.03298713, 0.009434878, -0.0129292775, -0.0075129587, -0.0064296946, 0.0035468154, 0.0112519665, 0.0087359985, 0.03438489, 0.0047873273, -0.045287415, -0.03466444, -0.027955195, 0.019289086, -0.006604415, 0.042491898, -0.0048222714, -0.026976764, 0.008107007, 0.028374523, 0.035503097, 0.034943994, -0.018869756, -0.03913727, 0.018450428, -0.016843006, 0.03885772, -0.0077575664, -0.05591039, 0.014327037, 0.023761915, 0.019568635, -0.038019065, -0.055071734, -0.015375358, -0.008701054, -0.005171711, -0.0010526879, 0.0048222714, 0.020547068, -0.016563453, -0.015165693, 0.0012929278, -0.0120906215, 0.020686844, 0.076597236, -0.026836988, 0.031030266, -0.0180311, 0.0108326385, -0.030051835, 0.03410534, -0.007897343, 0.016563453, -0.0112519665, -0.008456446, -0.024880122, -0.070167534, -0.005171711, -6.7703986e-05, -0.015235581, 0.0008430239, 0.025439229, -0.008561278, -0.010902526, 0.0112519665, 0.024460796, -0.0180311, 0.0074081267, -0.06709247, 0.03424511, 0.024181243, 0.024181243, -0.04556697, 0.041653242, 0.005765759, -0.010553086, 0.027675642, -0.0076177907, 0.0069887987, 0.014676478, -0.043610103, 0.017192446, 0.0010788959, -0.011391742, -0.02362214, -0.02362214, -0.009993982, 0.004018559, 0.004350527, 0.014117373, -0.020547068, 0.0071635186, -0.051996663, 0.04444876, -0.0137679335, -0.01216051, -0.038298618, -0.04752383, 0.02641766, -0.030610938, -0.027116539, 0.021944826, -0.018869756, -0.014047486, 0.024041468, 0.04864204, 0.0034594552, -0.038298618, 0.011601406, -0.012999166, 0.008596223, -0.0037390073, 0.0110423025, -0.02529945, -0.026277883, 0.0012317759, 0.011601406, 0.031170042, -0.024600571, -0.054512627, -0.004001087, -0.008107007, -0.016214013, 0.017611772, 0.0041583353, -0.0110423025, -0.033266682, 0.04752383, 0.0076177907, -0.03578265, 0.021385724, -0.0042107515, 0.012579838, -0.03857817, -0.0019481276, 0.024041468, 0.014536701, 0.0006289919, 0.015794685, 0.036900856, -0.0137679335, 0.015095805, 0.06038322, 0.0034769275, -0.043051, 0.019568635, -0.0010221119, -0.055071734, 0.036621306, -0.022364156, 0.036900856, -0.016633341, -0.028234746, 0.018170878, 0.0022888316, 0.034524668, 0.030610938, -0.031729147, -0.010692862, 0.016004348, -0.0071635186, 0.010273534, -0.015235581, -0.0034419834, 0.0123002855, -0.011531518, -0.01181107, -0.028933628, -0.0033196795, -0.0034245115, 0.03228825, 0.020407291, 0.006639359, 0.027955195, 0.0027780475, -0.033126906, 0.0072683506, 0.014676478, 0.004455359, 0.010133758, 0.028933628, -0.0037914233, -0.025579004, -0.02641766, -0.042771447, -0.032148473, -0.027955195, 0.026836988, -0.0016947837, 0.014327037, 0.007233407, 0.018869756, -0.049760245, 0.014117373, 0.019289086, -0.007233407, 0.028374523, 0.014396925, -0.041653242, -0.0032323194, 0.013278718, 0.0030750714, 0.02432102, -0.009784318, -0.017122556, -0.00092601584, 0.0052066552, 0.0104133105, -0.015654908, 0.00035817592, 0.0139775975, -0.021665277, -0.0065694707, -0.0031624313, 0.0215255, 0.010203646, -0.008351615, 0.006849023, -0.010343422, -0.0104133105, 0.006185087, -0.019848188, -0.01670323, -0.026697211, -0.036341757, 0.0047873273, -0.0013278718, -0.08889752, 0.020127742, -0.0012667198, 0.0006464639, -0.03885772, -0.03270758, 0.036621306, 0.0038263672, 0.0025334395, -0.027256314, 0.022783484, 0.0019393916, 0.06178098, 0.0044204155, 0.0026557436, 0.009085439, 0.007023743, 0.036341757, -0.008875774, -0.025998332, -0.008386559, -0.050878458, -0.015724799, 0.00024242395, 0.0011968318, 0.021245949, 0.043051, 0.0285143, 0.009644543, 0.005346431, 0.043051, -0.0089456625, -0.022923259, -0.015095805, 0.017541884, 0.043889653, 0.02362214, -0.019149309, 0.03718041, 0.0076527344, -0.009085439, -0.029213179, 0.0011618878, -0.0033196795, -0.032847356, 0.040814582, -0.017541884, 0.0032148473, 0.04137369, 0.0014938557, -0.0250199, 0.052555766, 0.013278718, 0.0015812156, 0.032847356, -0.011182078, -0.019149309, 0.021245949, 0.004857215, 0.0058705914, -0.0137679335, -0.009434878, -0.0010133758, -0.020966396, -0.0023063035, -0.0116712935, -0.019289086, 0.004507775, -0.020267516, 0.0180311, 0.010553086, 0.008281726, 0.024600571, 0.018590204, 0.069049336, 0.03089049, 0.06821068, -0.037459962, -0.017611772, 0.043610103, 0.011601406, -0.07827454, -0.019848188, -0.031309817, 0.0069887987, 0.021245949, -0.03340646, -0.032148473, -0.009504766, -0.0123002855, 0.015864573, 0.02781542, 0.0064296946, 0.01705267, 0.0028304635, 0.0077575664, -0.024041468, 0.0012841917, -0.023063036, -0.026138106, 0.015235581, -0.024740348, 0.031030266, -0.0131389415, 0.018450428, -0.015235581, -0.033825785, 0.042491898, 0.005101823, -0.0050319354, -0.019987963, 0.06373785, 0.00056347187, -0.018170878, 0.020966396, -0.013488382, -0.029352956, 0.0023412476, -0.029352956, 0.018869756, 0.005241599, -0.022783484, -0.047803383, 0.0110423025, -0.039975926, -0.019848188, -0.026697211, -0.0029702394, 0.008631167, 0.04137369, 0.028234746, 0.009434878, 0.026557436, -0.034804218, 0.0029178234, 0.004455359, 0.0031274876, 0.007233407, 0.027955195, -0.032148473, -0.04416921, 0.0133486055, -0.019987963, 0.017122556, 0.025718778, -0.015095805, -0.0250199, 0.03773951, -0.029772284, 0.04137369, 0.031729147, 0.025159676, -0.0028828795, 0.004857215, 0.055351283, -0.019289086, 0.056749046, -0.02222438, 0.009993982, -0.05031935, -0.007862399, 0.027675642, 0.014396925, -0.017611772, -0.015934462, 0.021245949, 0.0023761916, 0.018590204, -0.0005219759, -0.035223544, 0.005975423, -0.028234746, -0.012789502, -0.028094972, -0.018310653, -0.0075828466, -0.008037118, 0.040535033, 0.02641766, -0.019289086, 0.008002174, 0.05563084, -0.033266682, -0.015305469, -0.006604415, -0.0017384638, 0.0037390073, 0.049480695, -0.025998332, 0.00082555186, -0.023901692, 0.0037739512, -0.059824117, -0.0025683835, 0.04444876, -0.0112519665, 0.0031274876, 0.022084605, -0.056189943, 0.024880122, 0.009225214, -0.03466444, -0.010343422, 0.0012667198, 0.010483198, 0.008072062, 0.052555766, 0.03438489, -0.021944826, 0.005451263, 0.010063871, -0.037459962, 0.026277883, 0.012579838, 0.005101823, 0.027116539, -0.026138106, 0.011321854, -0.0064646387, -0.0112519665, -0.0077575664, -0.0019393916, 0.03270758, 0.018729981, -0.015864573, -0.032428026, 0.0020616956, -0.021805052, -0.020966396, -0.011601406, 0.013837821, 0.03913727, 0.059265014, 0.039696377, 0.06541516, 0.0031799036, -0.012230398, -0.017402109, 0.0015724797, -0.07044709, 0.01635379, -0.008386559, -0.01733222, -0.006289919, 0.01390771, -0.006254975, 0.005066879, 0.030750716, -0.016633341, 0.0075479024, -0.020267516, -0.0215255, -0.025718778, -0.0123002855, 0.06597426, -0.01320883, -0.0048222714, 0.026836988, -0.031170042, 0.01250995, 0.0123002855, -0.031309817, 0.018590204, 0.06373785, 0.05563084, -0.019149309, -6.551999e-06, 0.00056347187, -0.02222438, -0.027256314, 0.05283532, -0.0074081267, 0.017262334, -0.039975926, 0.019009532, -0.042212345, -0.031868923, 0.007443071, -0.043610103, -0.062899195, -0.017541884, 0.004647551, -0.0360622, 0.004001087, -0.024181243, 0.03424511, -0.030471163, 0.01181107, -0.008875774, -0.024740348, -0.0030401275, -0.0035817593, -0.02432102, 0.02362214, -0.018869756, 0.049201142, 0.15207626, 0.024740348, 0.030331386, -0.028094972, -0.023482366, -0.027396092, -0.020547068, 0.005800703, 0.03019161, 0.024740348, 0.018450428, -0.0017646716, 0.013278718, 0.00023805596, 0.016633341, 0.13027121, -0.027535867, -0.016074236, 0.06541516, 0.025159676, 0.0055211512, 0.017611772, -0.0034943994, -0.0039836154, 0.019568635, -0.0059404788, -0.029352956, -0.024740348, 0.0065694707, 0.015794685, -0.020547068, -0.011182078, 0.010972413, -0.0116712935, -0.012859389, 0.02529945, 0.027116539, 0.0043155835, 0.031309817, -0.03019161, -0.021385724, -0.0060453108, 0.026976764, 0.011950846, 0.036900856, 0.004333055, 0.008910718, 0.015934462, 0.023761915, 0.016144125, -0.0089456625, 0.052555766, -0.008072062, -0.024740348, -0.0131389415, -0.010273534, 0.0106229745, 0.0250199, -0.039696377, 0.026976764, 0.013278718, -0.042212345, -0.0015025918, -0.07072665, -0.0013715517, 0.031170042, 0.012230398, 0.020547068, 0.01942886, -0.023761915, -0.012230398, 0.0057308148, 0.015095805, -0.011741183, 0.0005591039, -0.0091553265, -0.0500398, -0.024041468, -0.01942886, 0.014746365, -0.011531518, -0.026976764, -0.030471163, 0.022084605, -0.015794685, 0.0053114872, -0.021944826, 0.010133758, 0.020407291, 0.020686844, 0.0071984627, -0.015724799, 0.019149309, 0.016493564, -0.0058356468, -0.037459962, -0.007338239, 0.031729147, -0.006080255, 0.026557436, 0.019289086, 0.0022888316, 0.0037040634, 0.010972413, 0.007897343, 0.035223544, 0.009784318, 0.0039311997, -0.022923259, 0.017681662, -0.012020734, 0.0024984954, 0.0034943994, 0.0285143, 0.0139775975, -0.005660927, 0.0007250879, 0.0042981114, -0.010343422, -0.018869756, -0.0250199, 0.016423678, -0.0032672633, -0.00971443, 0.004333055, 0.015095805, 0.04556697, -0.017681662, -0.0009085438, 0.013628157, -0.0007643999, 0.0032148473, 0.032428026, 0.008875774, -0.016633341, 0.0017734077, -0.0039486713, -0.02222438, 0.027396092, 0.020826621, -0.04193279, -0.01733222, 0.020826621, 0.012649725, -0.027535867, 0.022923259, -0.005241599, 0.01942886, -0.043889653, -0.0056259832, -0.026836988, 0.0037040634, 0.007827454, -0.008631167, -0.012370174, -0.019848188, 0.012649725, 0.00058967987, 0.017891325, 0.023063036, 0.01216051, 0.040535033, 0.031309817, 0.06821068, -0.020686844, 0.027535867, 0.005800703, -0.012230398, -0.021665277, -0.017891325, -0.0022713598, -0.019568635, 0.016773118, 0.023901692, 0.0075828466, 0.005975423, -0.008770942, 0.005066879, 0.025159676, -0.016004348, -0.019009532, 0.018729981, 0.0062200306, -0.013488382, 0.02879385, -0.008805886, -0.006010367, 0.052276213, 0.0035118714, -0.03885772, 0.0112519665, -0.020826621, 0.0118809575, 0.0108326385, 0.022364156, 0.0064296946, -0.021385724, -0.08833842, -0.02432102, 0.005451263, -0.0044204155, -0.0500398, -0.00036254394, 0.019568635, 0.02879385, -0.01250995, -0.010343422, 0.015794685, -0.004857215, -0.01181107, -0.018590204, 0.03019161, 0.035503097, -0.021385724, -0.0047873273, 0.0048222714, 0.009434878, 0.04137369, 0.011531518, 0.004717439, 0.0116712935, -0.018869756, 0.0060453108, 0.015095805, 0.03270758, -0.012649725, 0.01705267, -0.022643708, 0.014047486, 0.026976764, -0.02949273, 0.036621306, -0.006499583, -0.025439229, -0.03773951, 0.032428026, -0.00089107186, 0.019848188, 0.025718778, 0.018450428, 0.010902526, 0.0010657918, 0.031170042, -0.020966396, 0.0070936307, -0.019987963, 0.025579004, 0.016493564, 0.040814582, 0.0013715517, -0.0071635186, -0.014396925, -0.0360622, 0.024041468, 0.08833842, -0.0019568636, -0.026697211, 0.022783484, -0.026557436, 0.009434878, -0.019568635, -0.0010221119, -0.013698046, -0.045287415, 0.02222438, 0.008176895, -5.296199e-05, -0.012440061, 0.0076177907, -0.021665277, 0.0116712935, 0.005905535, 0.013628157, -0.0073032947, -0.0575877, -0.015724799, -0.029912058, -0.013069053, 0.032428026, 0.016423678, 0.029632507, -0.0029003515, -0.020407291, -0.018170878, -0.008631167, 0.0077925106, -0.0021490557, -0.040255483, 0.03885772, 0.0074780146, 0.03396556, 0.08274738, -0.016773118, -0.035223544, -0.015515133, -0.0039836154, -0.016843006, 0.02432102, 0.033825785, -0.040814582, 0.021944826, 0.02879385, -0.016563453, -0.024181243, -0.014816253, 0.032008696, 0.0011269437, -0.017541884, 0.01942886, 0.031729147, 0.012859389, 0.01320883, -0.0215255, 0.005066879, 0.023901692, 0.018729981, -0.026836988, -0.0118809575, 0.023482366, -0.020267516, -0.036621306, 0.008770942, -0.0011356799, -0.033126906, 0.006115199, 0.0065694707, -0.0123002855, 0.032008696, 0.05870591, -0.010902526, 0.015375358, -0.044728313, -0.010692862, -0.018170878, -0.0024810235, 0.0036341753, -0.036341757, 0.03089049, -0.004647551, 0.054792184, 0.00081244786, 0.0180311, 0.0505989, 0.009784318, 0.048362486, 0.019009532, 0.0036865913, -0.00044335192, 0.023482366, -0.014047486, 0.017751548, 0.032847356, 0.01733222, 0.042212345, 0.031729147, 0.019149309, -0.024740348, -0.008456446, 0.010273534, 0.015025917, 0.048362486, 0.028094972, -0.048921593, 0.0077575664, -0.00041059192, 0.0118809575, -0.0137679335, -0.032567803, -0.018170878, -0.04696473, -0.026697211, -0.006639359, 0.041653242, -0.0013890237, -0.027535867, 0.0215255, -0.043610103, 0.015165693, -0.016563453, 0.013628157, 0.023482366, 0.038298618, 0.0036865913, 0.0135582695, -0.0060453108, 0.022783484, -0.0044728313, -0.035223544, -0.017611772, 0.022503933, 0.029632507, -0.029912058, -0.030471163, -0.018869756, 0.009295102, -0.0017471997, 0.014676478, 0.036341757, 0.0031799036, -0.053114872, -0.024181243, -0.026138106, 0.0049271034, 0.02362214, -0.0006726719, 0.031170042, 0.010063871, 0.07072665, 0.0010264799, -0.019848188, -0.031030266, 0.012789502, 0.03885772, 0.017891325, -0.005556095, 0.00866611, 0.010902526, 0.0008430239, 0.029632507, 0.022783484, -0.020686844, 0.0028304635, 0.0017209917, 0.016633341, 0.0014152317, 0.006499583, 0.059544567, -0.043051, 0.030750716, 0.0575877, -0.006185087, 0.033126906, 0.009644543, 0.032847356, 0.04444876, -0.015305469, -0.040814582, -0.0056259832, 0.0034245115, -0.0012492477, -0.032567803, 0.054792184, 0.008875774, -0.012719614, -0.008421503, 0.00081244786, -0.036621306, 0.004507775, -0.025718778, -0.017751548, -0.007932287, -0.004036031, -0.015794685, 0.010553086, -0.0131389415, 0.01635379, -0.0023761916, -0.024041468, -0.010273534, 0.010692862, 0.0029877115, -0.023901692, 0.005975423, -0.004717439, -0.041094135, -0.00058967987, -0.015025917, -0.014676478, -0.028094972, -0.0046824953, 0.0108326385, 0.039416827, 0.022503933, 0.020686844, -0.020686844, 0.017751548, 0.0073731826, 0.060942326, 0.01942886, 0.025579004, 0.03718041, 0.056469493, 0.03019161, 0.04193279, -0.027675642, -0.009644543, -0.0073731826, 0.01942886, 0.021805052, -0.009085439, 0.024740348, -0.037459962, -0.017262334, 0.021245949, -0.047803383, 0.0037564794, -0.0057308148, 0.020686844, -0.02949273, -0.031030266, -0.045287415, -0.043051, -0.0024286075, -0.0052066552, 0.04724428, 0.018450428, 0.014536701, 0.005241599, -0.022783484, 0.01942886, 0.006849023, -0.008456446, 0.019848188, -0.009225214, 0.03773951, -0.0500398, 0.05171711, -0.010483198, -0.0180311, 0.014676478, -0.04416921, -0.050878458, 0.00866611, -0.0032148473, 0.032148473, -0.012649725, -0.010483198, -0.029213179, -0.021245949, -0.07939275, 0.0031799036, -0.016563453, -0.01942886, 0.0133486055, 0.0012841917, -0.015934462, 0.005241599, -0.0010395838, -0.043330554, -0.032567803, -0.017751548, 0.004892159, -0.017402109, -0.01320883, -0.021805052, 0.051158007, -0.022503933, -0.028654074, 0.0036167034, -0.052555766, -0.05283532, 0.020267516, -0.0050319354, 0.021805052, 0.037459962, 0.040255483, -0.0091553265, 0.0043679993, -0.012859389, 0.016563453, -0.005695871, 0.025159676, 0.00057657587, 0.00096532784, 0.004996991, -0.0034594552, 0.0045427196, 0.0360622, 0.027116539, -0.012649725, -0.0006508319, 0.019289086, 0.016773118, -0.010133758, -0.012789502, -0.024740348, 0.015305469, -0.014536701, -0.010273534, -0.043889653, 0.006185087, -0.019149309, 0.0110423025, -0.025159676, -0.0005088719, 0.0215255, -0.02641766, 0.005660927, 0.01076275, 0.013069053, 0.041653242, -0.04556697, -0.0053114872, 0.028933628, -0.03410534, 0.012230398, 0.03466444, -0.0015025918, -0.006185087, 0.021805052, -0.040814582, -0.006499583, -0.05395353, 0.02432102, -0.004507775, 0.014327037, -0.0034419834, 0.015165693, -0.024041468, 0.0061501428, -0.018729981, 0.0005023199, -0.01733222, -0.024880122, -0.014396925, 0.009854207, -0.01942886, 0.037459962, 0.037459962, 0.01181107, -0.013069053, -0.020826621, -0.021245949, 0.013069053, 0.004996991, 0.028234746, 0.005975423, -0.006359807, -0.006359807, -0.019848188, -0.046405625, -0.005765759, 0.035223544, 0.01111219, 0.018310653, 0.0018345597, -0.046405625, 0.025439229, 0.018170878, -0.021944826, -0.0089456625, -0.01670323, 0.021106172, -0.03857817, -0.058146805, -0.05591039, 0.012789502, 0.007827454, 0.0017646716, -0.0032847354, 0.020686844, -0.008805886, 0.051437557, 0.0029003515, -0.0014851197, -0.020407291, -0.01670323, -0.012719614, -0.005695871, 0.0059404788, -0.04444876, 0.029912058, -0.02222438, 0.0017122558, -0.021106172, -0.031170042, -0.023901692, -0.027955195, -0.0500398, 0.014047486, -0.01390771, -0.029352956, 0.0087359985, 0.0025509114, 0.015654908, 0.042491898, 0.004018559, 0.008561278, 0.0034769275, -0.006115199, -0.035503097, -0.03158937, 0.0095746545, 0.056189943, 0.030331386, -0.0133486055, 0.0069887987, -0.0008561279, 0.006744191, 0.019708414, 0.027116539, 0.014396925, 0.006359807, 0.04193279, -0.012579838, -0.022364156, 0.021665277, -0.021944826, 0.013278718, -0.016214013, 0.034524668, 0.0180311, -0.032008696, -0.012719614, 0.01390771, -0.0180311, -0.0059404788, -0.024460796, 0.01635379, -0.0034769275, -0.019987963, -0.015864573, 0.026836988, 0.012440061, 0.013488382, 0.0021228476, 0.03340646, -0.013698046, -0.012859389, 0.008246782, -0.0075828466, 0.035363324, -0.0010832638, 0.0180311, -0.019848188, 0.02222438, -0.014606589, -0.051437557, -0.010553086, -0.0032323194, -0.03857817, -0.019149309, 0.014816253, -0.048362486, 0.0039486713, -0.0129292775, -0.0011793597, 0.010902526, 0.0137679335, 8.299199e-05, -0.035363324, 0.018170878, 0.0123002855, -0.01425715, 0.03089049, 0.02362214, -0.041653242, -0.01250995, 0.0017821437, 0.031729147, 0.01698278, -0.0052066552, 0.057867255, 0.014676478, 0.035223544, 0.018170878, 0.032008696, -0.026836988, -0.005975423, -0.029073402, -0.020966396, 0.005136767, 0.0014152317, 0.04864204, 0.0019393916, 0.0037564794, 0.008631167, -0.0013540798, 0.01942886, -0.018310653, -0.029912058, -0.0069189104, 0.02879385, 0.028094972, -0.045287415, -0.02432102, -0.008211839, -0.011950846, 0.033546235, -0.0048222714, -0.020966396, 0.0180311, -0.053394422, 0.0032672633, 0.005800703, -0.023202812, -0.013069053, -0.01698278, 0.014047486, 0.020966396, -0.0024810235, -0.02781542, 0.012579838, 0.04444876, 0.0089456625, 0.00087359984, -0.0021228476, 0.020547068, -0.022643708, -0.004437887, -0.0035992314, 0.0065345266, -0.004001087, 0.020407291, 0.008910718, -0.025998332, 0.02362214, -0.016563453, -0.0120906215, 0.055071734, -0.05171711, -0.014816253, -0.0360622, 0.035642873, 0.029632507, 0.017821437, -0.009924094, 0.020267516, -0.045287415, -0.019987963, 0.0046824953, -0.022783484, -0.06010367, 0.014816253, 0.0026033276, -0.033126906, 0.023901692, -0.011321854, -0.012020734, -0.0131389415, 0.010692862, 0.013628157, 0.022783484, -0.018170878, -0.049201142, -0.009784318, -0.020547068, 0.0023237756, -0.007827454, 0.0072683506, -0.0015812156, 0.023063036, 0.010063871, -0.005381375, 0.019009532, -0.026138106, 0.01670323, 0.0006289919, 0.0013715517, 0.0038962553, 0.036341757, 0.009854207, -0.03718041, 0.005765759, -0.035083767, -0.017541884, -0.060662773, 0.019848188, -0.06178098, 0.029213179, -0.0069887987, -0.026836988, 0.006499583, 0.00062462385, -0.019149309, -0.00062462385, 0.050878458, 0.013069053, -0.01425715, -0.034524668, 0.00046300792, 0.091693036, -0.04444876, 0.06373785, 0.008631167, 0.03089049, 0.018590204, 0.009225214, 0.0033371514, 0.011391742, 0.039416827, 0.016423678, -0.054792184, -0.031729147, 0.028374523, -0.009504766, -0.0068839667, 0.008037118, 0.0036516474, -0.0129292775, 0.005171711, -0.0046824953, 0.0072683506, -0.0076177907, -0.0023237756, 0.012999166, 0.040535033, 0.0058356468, -0.016493564, 0.022084605, -0.012370174, 0.030471163, -0.020267516, 0.018450428, 0.015025917, 0.040814582, 0.019848188, -0.025858555, -0.035503097, -0.013698046, -0.012859389, 0.055071734, 0.015864573, -0.018310653, 0.025439229, 0.032428026, 0.008386559, 0.021944826, 0.019568635, 0.0067791347, -0.006499583, -0.0015899518, 0.005451263, 0.0009609599, 0.0041758073, 0.00849139, 0.0575877, -4.859399e-05, 0.028234746, 0.047803383, -0.020547068, 0.

Amazon data embedding

In [102]:
point_structs = []
for i, data in enumerate(data_to_embed):
    vector_embedding = generate_embedding(data["description"])
    point_struct = PointStruct(
        id=i,
        vector=vector_embedding,
        payload=data

    )
    point_structs.append(point_struct)

In [103]:
point_structs

[PointStruct(id=0, vector=[-0.005190131, 0.031140786, 0.0033573657, 0.019203484, 0.0147269955, -0.026729172, -0.04437562, -0.029713498, -0.033995356, -0.042040057, 0.00674717, 0.09861249, -0.029194485, 0.005027939, 0.01790595, 0.025172133, 0.02698868, 0.03451437, 0.030362265, -0.012326561, 0.049306244, 0.008823222, -0.0049306243, -0.0005919993, -0.0032276125, 0.039964005, 0.00012215054, -0.0024004355, -0.0016543542, -0.03607141, -0.00040750633, -0.010899275, -0.06591466, -0.009017852, -0.0141431065, -0.0047684326, 0.049046736, -0.03892598, 0.0010785741, 0.044116113, -0.01946299, -0.0045413645, -0.038406968, 0.02218781, 0.00327627, 0.009212482, 0.018684471, -0.024134109, 0.0061632805, 0.039444994, -0.0358119, -0.004281858, -0.02815646, -0.0027085994, 0.022706822, -0.004573803, 0.0026923805, -0.029973004, 0.025561394, 0.0358119, -0.0008271771, 0.0114831645, -0.05475588, -0.008563716, -0.06850973, 0.016997678, 0.035292886, 0.028805226, 0.03451437, -0.0020922713, -0.010315385, 0.032438315, -0.0061632805, 0.015505515, 0.045413643, 0.008823222, 0.03451437, -0.023096083, -0.062541075, 0.018165458, -0.0071688686, 0.009212482, -0.02737794, -0.0010461357, -0.0038439406, 0.045154136, -0.03204906, 0.02737794, -0.007266183, 0.01907373, 0.0635791, -0.046711177, 0.05319884, -0.018814223, 0.016543541, 0.0258209, 0.027637446, 0.02621016, 0.03282758, 0.0022869015, -0.0038277216, 0.011029028, 0.0073310593, 0.031270538, -0.044635125, 0.0046386793, -0.055015385, -0.005190131, -0.0358119, 0.020890275, 0.019203484, 0.0018408744, -0.003779064, -0.058907982, -0.0012326561, -0.0031951743, 0.021539044, 0.01907373, -0.00079879357, 0.0068120467, 0.016543541, -0.014597243, -0.007947387, -0.0023355589, 0.0049955007, -0.035552397, 0.059167493, -0.04800871, 0.0125860665, -0.0010096426, 0.037368942, -0.011677794, 0.036849927, -0.0027896953, -0.0008636702, 0.021668795, 0.010574891, 0.04126154, 0.051901307, 0.0125860665, -0.013818723, -0.011093905, 0.019592743, 0.007687881, 0.01213193, 0.0068120467, 0.007947387, -0.0026275036, -0.027507693, 0.0042169816, 0.009471989, -0.037628446, -0.029324237, -0.0397045, 0.012067054, 0.00022808192, -0.0020922713, -0.046711177, 0.035033382, -0.00040547896, -0.0016624638, -0.028026707, 0.0059686503, 0.0358119, 0.008433963, 0.01673817, -0.0516418, 0.0002777531, 0.031270538, 0.03607141, -0.0016786829, 0.017516691, -0.0009204372, 0.07318085, 0.03217881, 0.044116113, -0.028415965, 0.0141431065, -0.01946299, 0.02893498, 0.025431642, -0.012326561, 0.055793907, -0.007947387, -0.0063579106, -0.010574891, 0.0038277216, -0.017646443, -0.061762556, -0.015051379, 0.037109435, -0.007460813, 0.026080405, 0.033735853, -0.030492019, 0.0136240935, -0.006844485, -0.022317562, -0.01329971, -0.010315385, -0.016543541, 0.013818723, 0.055015385, -0.049825255, -0.023355588, -0.0036979683, -0.0071364297, -0.005871335, -0.015246009, 0.016867926, 0.02815646, -0.0053523225, -0.0104451375, -0.06850973, 0.018035704, -0.0044764876, 0.009991001, -0.0048333094, -0.0034222426, -0.0093422355, -0.015181133, -0.003908817, -0.043078087, 0.008271771, -0.011158781, -0.000944766, -0.016154282, 0.00072986213, -0.02063077, -0.034773875, 0.028026707, 0.022966329, 0.019592743, -0.0037141873, 0.010315385, 0.022058057, -0.011029028, 0.018943978, -0.007558128, -0.02698868, -0.0147269955, 0.006682293, -0.02659942, -0.0474897, -0.01310508, -0.013364586, 0.013948477, 0.0028059145, -0.026080405, 0.014337737, -0.029583747, 0.0028383527, 0.030751524, -0.04956575, -0.0006325472, 0.025950653, 0.008563716, 0.033735853, 0.032308564, 0.0052874456, -0.012456314, -0.045413643, -0.033087082, -0.006682293, 0.013234833, 0.034254864, -0.02426386, -0.017127432, 0.019722497, -0.036330916, -0.008239333, -0.014207982, -0.0055793906, 0.017127432, -0.036330916, -0.0018165457, 0.0035357766, -0.030232511, 0.044116113, 0.009471989, -0.0030978594, -0.016997678, 0.020371264, 0.017127432, -0.028026707, 0.012002178, 0.03295733, 0.029583747, -0.01602453, -0.0035682148, 0.0069742384, 0.023615094, 0.0104451375, -0.018424964, 0.0019706278, -0.0258209, 0.030621773, -0.0021084908, -0.03217881, 0.018684471, -0.033995356, 0.0065201013, -0.0014516147, -0.020890275, 0.01641379, 0.013818723, -0.018165458, -0.017386938, 0.021928301, -0.034254864, 0.009666619, 0.006876923, -0.0015408201, -0.019333238, 0.035292886, 0.029583747, -0.031530045, -0.013818723, -0.051382296, -0.0474897, 0.025950653, -0.01407823, 0.016543541, 0.014921626, -0.009536865, 0.022836577, -0.03295733, 0.03295733, -0.021668795, -0.042299565, -0.016284036, 0.0031627358, -0.046711177, -0.016543541, -0.027118433, 0.030232511, -0.012456314, -0.00655254, 0.0035682148, 0.05371785, 0.0044440497, -0.04178055, -0.032697823, -0.051901307, -0.0043142964, -0.0004014242, -0.010834398, 0.049825255, -0.020760523, 0.0059686503, 0.043856602, -5.879445e-05, 0.02815646, 0.012715821, 0.03204906, 0.06695268, 0.034254864, -0.016867926, -0.035552397, 0.010185632, 0.043856602, 0.007979826, -0.033087082, 0.015959652, 0.008433963, 0.009471989, -0.017516691, -0.014337737, -0.006649855, 0.015765022, 0.008077141, -0.015116256, 0.023615094, -0.06435762, 0.0069417995, 0.013883599, 0.021020029, -0.022577068, -0.01907373, 0.007882511, -0.017386938, -0.0027896953, 0.0019787373, -0.002140929, 0.049046736, -0.0053523225, -0.010834398, -0.021149782, -0.021149782, 0.031400293, 0.024134109, -0.033087082, 0.037628446, 0.017516691, -0.0053523225, 0.022317562, -0.051901307, 0.017257186, 0.014986502, 0.045673154, 7.552046e-05, -0.018424964, -0.022836577, 0.023615094, 0.014272859, 0.06306009, -0.0028059145, -0.024523368, -0.0047684326, 0.043078087, -0.0041845427, 0.0012326561, -0.07525689, 0.014402613, -0.018424964, -0.0024166547, 0.0049630627, -0.024782876, 0.01349434, -0.024134109, 0.008693469, 0.033216838, 0.008758346, -0.0008920537, -0.02218781, -0.0044440497, 0.01349434, -0.02426386, -0.0025950654, 0.009861249, 0.0147269955, -0.023615094, -0.006001089, -0.0005190131, 0.039964005, -0.028675474, 0.010315385, -0.009861249, -0.029583747, 0.035033382, 0.0016056967, -0.06435762, 0.018684471, 0.0034222426, 0.011158781, 0.035292886, -0.03256807, -0.04178055, -0.0024815314, 0.0020030662, -0.004087228, 0.030232511, 0.046711177, 0.035033382, 0.032697823, 0.029973004, -0.0027248187, 0.021020029, -0.013234833, -0.0063254717, -0.007493251, 0.035033382, 0.012456314, -0.018424964, -0.028026707, -0.025950653, 0.045413643, -0.0011839987, 0.0020517237, 0.015116256, -0.0008758346, 0.003989913, -0.05735095, -0.037368942, 0.0074283746, -0.008628593, -0.016608419, 0.021668795, 0.0048657474, 0.06954775, -0.0036817489, 0.018035704, 0.049306244, -0.016089406, 0.021149782, 0.049825255, -0.0258209, -0.031919304, -0.0062930332, -0.031530045, -0.007006677, -0.044635125, -0.070066765, -0.009471989, 0.0073310593, -0.052939333, 0.030232511, 0.011223658, 0.07266183, -0.017776199, 0.013364586, -0.024004355, -0.0071364297, 0.0051576924, 0.034773875, 0.0125860665, 0.0070715533, 0.009666619, -0.010964151, 0.0021733672, 0.028415965, 0.0015732583, 0.034254864, 0.002757257, 0.010769522, -0.017516691, -0.024134109, 0.034254864, 0.05319884, 0.01310508, -0.0025301888, -0.010510014, -6.7917725e-05, 0.024653122, -0.028026707, -0.018165458, 0.015181133, -0.02140929, 0.04645167, -0.017776199, 0.007947387, -0.03451437, 0.025431642, 0.009017852, -0.0054820753, -0.0008109579, 0.04178055, 0.005027939, -0.011029028, 0.018814223, 0.014337737, 0.10120755, 0.02024151, -6.8424575e-05, 0.0716238, -0.04697068, -0.036849927, -0.040742528, 0.01602453, 0.01329971, -0.042559072, -0.009861249, 0.04437562, -0.009926125, -0.010250508, 0.028545719, 0.0017678883, 0.006130842, -0.011677794, 0.1390955, -0.016867926, -0.033735853, -0.012067054, 0.013559217, 0.043078087, 0.033995356, 0.055534396, -0.03217881, -0.005319884, 0.0019057512, 0.0024166547, -0.007266183, -0.035552397, -0.018684471, -0.035292886, 0.018295212, 0.008758346, -0.008823222, 0.0104451375, -0.017646443, 0.015181133, 0.043078087, 0.039185487, -0.036849927, -0.010899275, -0.006195719, 0.041521046, -0.009731495, -0.022317562, -0.0009812592, -0.029583747, -0.010899275, 0.01641379, -0.009926125, 0.009407111, 0.059686504, 0.014662119, 0.0358119, 0.03607141, -0.012650943, 0.012067054, -0.02659942, -0.028415965, 0.014532366, 0.0055469526, -0.049306244, -0.026858926, -0.01407823, -0.0009528756, 0.052939333, 0.012715821, 0.008628593, 0.067471705, 0.006455225, 0.008823222, 0.018684471, -0.027767198, 0.066433676, 0.005838897, -0.033216838, -0.022447316, 0.0077527575, 0.0017597787, -0.045673154, 0.017386938, -0.0023355589, 0.04437562, -0.0072013065, -0.039444994, 0.005027939, 0.0032276125, 0.023225835, -0.04697068, -0.026729172, 0.0007176978, 0.039185487, -0.044894632, -0.027637446, 0.015181133, 0.01310508, -0.015700147, 0.019722497, -0.006649855, -0.024912627, 0.02621016, -0.00081501267, -0.024782876, 0.033735853, -0.0029356675, 0.05267983, 0.0047359946, 0.009407111, 0.017127432, -0.040742528, -0.016997678, -0.014402613, -0.0077203196, -0.018295212, 0.05371785, 0.016867926, -0.039444994, -0.009601742, 0.02348534, -0.023096083, 0.0397045, 0.008109579, 0.0141431065, 0.037628446, 0.018295212, -0.022836577, -0.026858926, 0.06202206, -0.02698868, 0.010639768, 0.00053117744, -0.019722497, -0.022058057, -0.03607141, 0.037109435, 0.02426386, -0.009731495, -0.005255007, 0.0036006533, -0.0032113935, -0.0054496373, -0.007233745, 0.0030492018, -0.011223658, -0.03282758, -0.029843252, -0.011353411, 0.01349434, 0.021539044, -0.019982003, 0.0055469526, -0.03451437, -0.0033573657, -0.0062605953, 0.0027410376, -0.043856602, 0.0039250366, -0.029843252, -0.008952975, -0.02621016, 0.019592743, 0.025691148, -0.0056767054, -0.040742528, 0.021279536, 0.022966329, -0.018424964, -0.0063254717, -0.020890275, -0.04697068, 0.011093905, 0.0049955007, -0.0070715533, 0.008369085, -0.0030167636, 0.0435971, 0.025301887, -0.015246009, -0.0010623549, -0.016997678, 0.017127432, 0.0036817489, -0.017776199, -0.036590423, 0.02621016, 0.038666476, -0.02737794, -0.010380262, 0.01907373, -0.017646443, -0.030492019, 0.035292886, 0.002254463, 0.017516691, -0.02218781, 0.024523368, 0.020111756, -0.009731495, 0.020760523, -0.004800871, 0.015375762, 0.0060984036, -0.006422787, 0.0033087083, 0.0047359946, 0.008304209, -0.016997678, 0.010185632, 0.0024815314, -0.0042494196, 0.061243545, 0.00022706822, 0.0068120467, 0.009082729, 0.005255007, -0.02659942, 0.00077446486, 0.050603773, 0.015310886, 0.017516691, -0.022317562, -0.04281858, 0.014856749, -0.02140929, 0.006876923, -0.0032113935, -0.0014678338, 0.00061632803, 0.016219158, 0.024912627, 0.024393614, 0.032438315, 0.020111756, -0.021149782, -0.031919304, -0.02218781, -0.04048302, -0.010834398, 0.016089406, 0.024004355, 0.022447316, -0.009407111, 0.028026707, 0.005125254, -0.030362265, 0.013883599, 0.037887957, 0.008952975, -0.009666619, -0.009212482, 0.012845574, -0.014337737, -0.04852772, 0.038666476, 0.03607141, 0.022706822, 0.018684471, -0.028805226, 0.0046386793, 0.017386938, 0.020760523, 0.035552397, -0.049046736, -0.009536865, -0.070066765, 0.022706822, 0.0069417995, -0.0037304065, 0.023096083, 0.013559217, 0.038666476, -0.009926125, -0.010510014, 0.012780697, -0.06850973, -0.033995356, 0.022577068, -0.022706822, -0.035033382, -0.024782876, 0.058129463, -0.025172133, -0.02179855, -0.016997678, -0.009277359, -0.0063903485, 0.0358119, 0.00655254, -0.023615094, 0.045932658, -0.026080405, 0.008498839, -0.01602453, 0.029713498, -0.005514514, 0.029583747, -0.0046386793, -0.005092816, 0.0435971, 0.023096083, 0.032438315, -0.031400293, -0.02426386, 0.027507693, -0.021668795, 0.03295733, -0.0009974783, 0.015700147, -0.009212482, 0.017386938, 0.04100203, -0.018424964, 0.037628446, -0.03217881, -0.005514514, -0.010704645, 0.0027085994, -0.035552397, -0.032308564, 0.028286213, -0.020760523, -0.034773875, -0.025042381, -0.0007014786, -0.024782876, -0.016543541, -0.01641379, 0.07058577, 0.0006933691, -0.0028383527, -0.0049955007, -0.023615094, -0.004281858, 0.0358119, 0.024393614, 0.044894632, 0.0054820753, -0.015959652, -0.0028059145, 0.024393614, 0.03607141, 0.0067147315, -0.0031627358, 0.01907373, 0.059167493, -0.016284036, -0.039964005, -0.013364586, 0.0059686503, -0.043856602, 0.0014921626, 0.085118145, 0.008888099, -0.018035704, -0.025431642, -0.009212482, -0.011807547, -0.012845574, -0.016867926, 0.01641379, 0.016867926, -0.04048302, -0.05631292, -0.021279536, 0.0075905663, -0.01213193, -0.012521191, 0.0397045, 0.023874601, 0.033216838, -0.0034546808, -0.051901307, 0.006001089, -0.023096083, -0.006228157, 0.0042494196, -0.035292886, 0.0069093616, -0.008433963, -0.040223513, -0.045932658, 0.02063077, -0.014402613, -0.009666619, -0.035292886, 0.038666476, -0.022317562, -0.004379173, -0.045932658, -0.020501016, -0.031659797, -0.04956575, -0.015635269, -0.036590423, 0.018295212, -0.025431642, 0.008012265, 0.039185487, 0.0071688686, 0.016997678, 0.01407823, 0.058907982, -0.013753846, 0.0042494196, 0.0055469526, 0.024523368, 0.02815646, 8.6671134e-05, 0.011612917, -0.0004602186, -0.045154136, -0.021539044, -0.009536865, 0.03295733, -0.034773875, 0.0057740207, 0.0136240935, -0.028545719, 0.0047035557, 0.01213193, -0.020371264, -0.021279536, -0.022836577, -0.0057415823, -0.002254463, 0.0062930332, 0.012845574, 0.0025139695, 0.022836577, 0.029324237, -0.0069742384, -0.00012215054, 0.007006677, -0.0011758889, 0.0062605953, 0.023355588, -0.0053523225, -0.014856749, -0.0071688686, -0.033995356, 0.014662119, -0.017386938, -0.0046711178, 0.025042381, 0.016997678, -0.012002178, -0.040223513, 0.0035682148, -0.040742528, -0.036849927, -0.0040385704, 0.021020029, 0.038666476, -0.0077203196, -0.0065849787, 0.028675474, 0.01446749, 0.009471989, 0.018943978, 0.025301887, -0.0032276125, 0.010639768, -0.033995356, 0.035292886, 0.038666476, 0.009601742, 0.030102758, -0.021539044, 0.0026275036, -0.019592743, -0.020760523, 0.034773875, 0.016154282, 0.0017922171, -0.021149782, 0.015116256, -0.011223658, -0.0005473966, 0.011158781, -0.02737794, -0.008758346, 0.0035033384, 0.0019706278, 0.0066174166, 0.0035195574, 0.031659797, -0.005514514, -0.008433963, -0.021149782, -0.008271771, 0.017776199, -0.020501016, 0.0039574746, 0.006065965, 0.025950653, -0.023225835, -0.018684471, -0.008628593, -0.041521046, 0.018295212, -0.010315385, -0.004071009, 0.011288534, 0.0033411465, 0.0397045, 0.026080405, 0.050344266, -0.015310886, 0.012261684, -0.022706822, 0.012456314, 0.0041845427, 0.017646443, -0.032308564, -0.015570393, 0.0009407112, 0.010574891, 0.0052225688, -0.052939333, 0.054236867, -0.0036493107, -0.011093905, -0.021020029, 0.014402613, 0.025042381, 0.0021571482, -0.023355588, 0.042040057, -0.004800871, -0.04956575, -0.022577068, 0.002562627, 0.0022706822, 0.0053523225, 0.032438315, 0.008563716, 0.026729172, -0.025691148, 0.005611829, -0.0061632805, 0.036849927, 0.0016624638, -0.0028383527, 0.030492019, 0.008044703, 0.0032276125, -0.01985225, -0.05319884, 0.052939333, 0.034773875, -0.0037466255, 0.005092816, -0.022577068, 0.0057091443, -0.013234833, -0.050603773, 0.013364586, 0.0035033384, 0.020760523, 0.016154282, -0.037368942, 0.008109579, 0.031659797, 0.062800586, 0.008433963, 0.006422787, 0.0041521047, 0.026729172, 0.015440639, 0.004508926, 0.005319884, 0.014986502, 0.0021571482, -0.019592743, -0.019333238, 0.0057091443, 0.005319884, 0.01310508, -0.017386938, -0.014402613, -0.015959652, 0.013234833, 0.021539044, -0.007558128, 0.018165458, 0.0021571482, -0.010510014, -0.02374485, 0.0125860665, 0.022577068, -0.015051379, 0.0069093616, 0.025301887, 0.01907373, -0.00043386247, 0.01602453, 0.013040203, -0.0147269955, 0.019333238, 0.043078087, -0.024653122, 0.0063903485, -0.050084762, 0.019333238, -0.012975327, -0.0030167636, 0.021020029, 0.036590423, -0.0039412556, -0.0104451375, 0.015440639, 0.0065849787, 0.031919304, -0.07525689, -0.024393614, 0.005514514, -0.0057091443, -0.0070715533, -0.0136240935, 0.025301887, -0.018424964, -0.0008190675, -0.011288534, 0.027118433, 0.019722497, -0.028286213, 0.013818723, -0.014013354, 0.024912627, -0.023615094, 0.014013354, -0.011158781, -0.015310886, 0.00032235577, -0.025172133, 0.0067796083, -0.007266183, -0.0046386793, 0.01673817, 0.0016705733, -0.026469667, 0.042299565, 0.015829898, -0.024653122, -0.0055793906, -0.012845574, -0.043078087, -0.02140929, 0.0012569848, -0.00019665729, 0.008271771, -0.0033898042, 0.017257186, 0.0147269955, -0.043078087, 0.015829898, -0.033995356, -0.008563716, 0.011612917, 0.0028545721, -0.01985225, -0.030621773, 0.007947387, -0.016154282, 0.042040057, -0.011288534, 0.026858926, -0.008563716, 0.045932658, -0.0039412556, -0.042299565, -0.025431642, 0.007493251, 0.008888099, -0.01946299, -0.01291045, -0.012456314, -0.015635269, 0.009666619, 0.002562627, -0.038666476, -0.06591466, -0.0069742384, -0.009861249, 0.025561394, -0.02737794, -0.030492019, -0.0049955007, 0.059686504, -0.015894774, 0.024523368, 0.009731495, 0.009082729, 0.014532366, 0.055534396, -0.006649855, -0.024134109, -0.047749203, 0.011353411, -0.02374485, 0.025172133, -0.010704645, -0.009796372, -0.0030492018, 0.067471705, 0.055534396, -0.006001089, 0.0007014786, -0.010769522, -0.006033527, -0.00045008166, -0.005838897, -0.02024151, -0.039444994, 0.008888099, 0.0041358853, 0.009796372, -0.04048302, 0.00674717, -0.00013684915, 0.025431642, 0.039964005, -0.019592743, -0.0063903485, -0.00674717, -0.015765022, 0.016997678, -0.0063903485, -0.022317562, 0.001329971, -0.029583747, -0.0075256894, 0.0013137518, -0.01790595, 0.02737794, 0.012521191, 0.012715821, -0.009731495, -0.0013786285, 0.023874601, -0.030232511, 0.012456314, -0.011418289, -0.018554717, 0.01985225, -0.0015246009, -0.07525689, -0.006422787, 0.0114831645, -0.014532366, -0.01174267, -0.021539044, 0.020890275, 0.00655254, -0.005092816, -0.028286213, -0.0034060234, -0.009666619, 0.016219158, 0.008174456, -0.0073634977, -0.038666476, -0.009147606, -0.005384761, 0.010055878, 0.015635269, -0.05683193, 0.018684471, 0.0048657474, 0.007914949, 0.01174267, 0.0141431065, 0.014532366, -0.033735853, -0.013883599, -0.033735853, 0.009082729, -0.022577068, 0.027118433, 0.005644267, 0.0013137518, 0.026729172, -0.037628446, 0.012456314, -0.028026707, 0.022317562, 0.01368897, 0.0147269955, 0.009407111, 0.0051576924, -0.0125860665, -0.03607141, -0.0011921081, 0.070066765, 0.018684471, 0.011807547, 0.015116256, -0.027118433, -0.0034384616, -0.011223658, 0.008498839, -0.0042494196, 0.008628593, -0.020890275, 0.014402613, -0.0023842163, 0.015959652, 0.01310508, 0.018035704, 0.0435971, -0.0053523225, -0.019982003, -0.038406968, 0.008628593, 0.011029028, 0.01790595, -0.012391438, -0.00025241065, -0.0056767054, -0.037628446, 0.0034871192, -0.0014678338, -0.016478665, 0.033995356, 0.006001089, -0.015246009, 0.007882511, 0.008174456, 0.01946299, 0.009471989, 0.0011191219, 0.01907373, 0.02737794, -0.033216838, 0.04178055, -0.022447316, -0.032697823, -0.03178955, 0.017646443, 0.0015164913, -0.019982003, -0.014013354, -0.0031302976, 0.024134109, 0.0077527575, -0.01946299, -0.07214282, -0.000636602, -0.01174267, -0.05683193, 0.026729172, 0.040223513, 0.015765022, 0.013234833, -0.021668795, -0.055015385, 0.0007379717, 0.015310886, 0.002449093, 0.012326561, 0.0016056967, -0.021020029, 0.017516691, -0.020501016, -0.046711177, -0.044116113, 0.005871335, -0.022836577, -0.034773875, -0.0063903485, -0.0023517779, 0.016608419, -0.011158781, 0.007006677, 0.03178955, 0.0042169816, -0.035292886, -0.0048333094, -0.0033087083, -0.030362265, -0.010639768, -0.0028383527, -0.010120755, -0.045154136, -0.021149782, 0.029194485, 0.012845574, 0.0041034473, 0.0063254717, -0.003779064, 0.0011434507, -0.089789264, -0.00010136974, -0.0049306243, -0.012975327, -0.004898186, 0.0059362124, 0.025691148, -0.030881278, -0.025431642, 0.001889532, 0.0029194485, 0.015635269, -0.016867926, 0.022317562, 0.06202206, -0.039185487, 0.020371264, 0.0060984036, 0.017257186, 0.020371264, 0.013169957, -0.0052874456, -0.025561394, -0.020890275, -0.008823222, 0.010704645, 0.0041034473, 0.0014435052, 0.010055878, -4.2828713e-05, 0.023225835, 0.02374485, 0.03282758, -0.0062930332, -0.0054820753, -0.0095

In [95]:
len(point_structs)

50

Writing embeddings to Qdrant

In [104]:
qdrant_client.upsert(
    collection_name="Amazon-items-collection-01",
    wait=True,
    points=point_structs
)

UpdateResult(operation_id=0, status=<UpdateStatus.COMPLETED: 'completed'>)

In [105]:
def retrieve_data(query,k=5):
    query_embedding = generate_embedding(query)
    results = qdrant_client.query_points(
        collection_name="Amazon-items-collection-01",
        query=query_embedding,
        limit=k
    )
    return results

Testing Retrival

In [106]:
retrieve_data("What kind of refrigerators do you offer",k=10).points

[ScoredPoint(id=40, version=0, score=0.3624581, payload={'description': 'Classic Retro 3.5 Cu.Ft. Chest Freezer and Refrigerator All in One, Includes Rolling Wheels, Portable, Indoor/Outdoor Use, Lock and Keys, Removable Basket, Adjustable Temperature Dial with GaugeRETRO DESIGN: Its chrome accents and retro design details harkens back to the cool vibes of record spinning jukebox and shiny muscle car eras. FROM FRIDGE TO FREEZER: Versatile temperature cooling settings ranges from 45F to -20F, allowing you to either keep beverages cold, ice frozen or anything in between. SPACIOUS CAPACITY: This unit has a 3.5 Cu. Ft. capacity with refrigerator & freezer capabilities, plenty of room for beverages, meats, and more. USE IN ANY SPACE: It’s a fabulous addition to any party or rec room, office, or apartment to serve the essential need of keeping water, soda, pizza, ice, or ice cream cold. LOCK IN THE CHILL: The heavy duty gasket creates a tight seal and prevents any cold air from escaping. EASY TO ROLL: Four bottom wheels make it easy to move the fridge without strain to wherever you need it. INCLUDED FEATURES: Removable wire storage basket, lock & keys, ice scraper, and bottle-opener attachment are all included with your refrigerator and freezer. INDICATORS: LED power & running status indicator and temperature gauge allow you to always view the status of your unit.', 'images': 'https://m.media-amazon.com/images/I/41vIBC6LotL._AC_.jpg', 'rating_number': 129, 'price': 249.99, 'average_rating': 4.2, 'parent_asin': 'B0B9C89D2Z'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=4, version=0, score=0.35855386, payload={'description': 'WANAI Beverage Refrigerator Cooler Mini Fridge Glass Door 125 Cans Beer Fridge Drinks Organizer for Soda Wine Small Refrigerator with 7 Thermostat 3 Shelves LED Lights for Home Bar Office🥇【Practical & Versatile Beverage Cooler】WANAI beer fridge glass door is an ultimate fridge to chill soft drinks, beers, wine, champagne, snacks for family gatherings, freeing up space in your main refrigerator. It is ideal to use anywhere in your apartments, home kitchen, offices, parties, bars, restaurants and so on. 🥇【Powerful Cooling】Our can mini fridge also as a drinks cooler features energy efficient advanced technology, consistent and uniform temperature supply inside. With a super quiet R600a compressor that cool quickly, keeps sound at 40 dB, so you can rest easy and enjoy peace of mind. 🥇【Stylish Design】Black body & special stainless steel exterior --Complete with recessed door handle & 2 layers of tempered glass door, blends beautifully with any home or office decor. Interior soft blue LED light looks amazing(can be turned off) when it lights up, adds atmosphere while keeping drink selection effortless. 🥇【Blue LED & Smart Control】Thanks to mechanical button to adjust temperature, you can simple adjust the temperature from 32℉ to 50℉, and turn the interior LED light on or off. 🥇【WARRANTY SERVICE】Our mini refrigerator3.2 cu.ft have 1-year warranty and 30-day return policy. If there is any problem with the product, customers could contact us first,and we will try to give a 100% satisfied solution.', 'images': 'https://m.media-amazon.com/images/I/51bY2oo5MhL._AC_.jpg', 'rating_number': 108, 'price': 199.99, 'average_rating': 4.2, 'parent_asin': 'B0C2PVJMHB'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=38, version=0, score=0.32534936, payload={'description': 'Replacement for Refrigerator Wɑtеr Ｆilter - Pack of 1 (Packaging May Vary)Compatible models:.The list models is for reference purpose only, we are not sponsored by the original brand. Easy Installation: Perfect fit your refrigerator without risk of leakage. 3s installation without any tool required. Worry Free Order: We extend the return window to 180 days, more than happy to assist you with any quality issue. This product may come in different packaging due to upgrades, but there is no need to worry as it will still be compatible with your refrigerator. Please be assured that we have optimized its design to ensure proper fit and function. Muti-stage Filtration Technology: We adopt advanced coconut shell carbon block and two separated ionization filtration stages, ensures you always get pure water with noticeable taste. Effectively Filtration Performance: Ｆilter reduces chlorine, taste and odor, lead, mercury and other harmful heavy metals, while remain beneficial minerals like calcium and magnesium in Ｆiltered water.', 'images': 'https://m.media-amazon.com/images/I/31WmlcdBsIL._AC_.jpg', 'rating_number': 158, 'price': None, 'average_rating': 4.4, 'parent_asin': 'B09RZSRZBB'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=5, version=0, score=0.30917397, payload={'description': '2 Pack Fridge Drawer Organizer, Refrigerator Organizer Bins, Pull-out Refrigerator Storage Drawer Bins Box, 12" Length, Refrigerator Pull out Under Shelf Holder Vegetable Veggies Fruit ContainerPlease Note & Measure the fridge shelf before buying : The shelf length range should be 11.8” - 17”, the shelf thickness must be less than 0.6”. It is featured with Extendable Rails Design -The freezer organizer bins design with a smooth spring pull rod. It is adjustable. This fridge drawer is not for slanted or curve downward. 2 Pack, Unique design, 50%+ Space Saving Fridge Organizer Drawer - 2 Pack refrigerator organizer bins feature with hanging & pull-out design, perfect for taking advantage of dead space under the refrigerator plate. Expand the usable space for more than 50% to make your fridge sorted and organizer in order. Transparent, Pull-out with Built-in Handle - Visable clear design makes the fridge storage containers easier to locate and find your items quickly. No need to open the bags and rummage through them one by one. The practical, integrated handles facilitate the removal and flexible movement of the kitchen storage units. 1 Bear Shaped Towel for Easy Maintain, Healthy & Safety - Fridge drawer organizer bins are made of food-grade PET & ABS material, BPA free. Refrigerator drawer organizer bins come with 1 x bear shaped maintain towel. Just untie it, it is a square towel for easy maintain the food storage containers. Dividers Freely for Your Various Needs - Optional insertable dividers are equipped inside the refrigerator storage box. You can divide the fridge drawer into 4 grids, 2 grids or without grids. Fridge organizer drawer is great for your daily storage needs, especially for small things. Making our refrigerator storage tidier. Portable & Stackable for Small things - You can using the refrigerator bins stacked or side-by-side. Help for maximize your fridge or kitchen space, make organizing and everyday living a little easier. This organizer bin for the fridge is ideal for fruits, meat, milk, salad dressing, drink bottles, canned food, and packaged food, condiments, jelly, and more. Say Goodbye to the Chaotic - Package included: 2 x fridge organizer bins, 4 drawer dividers & 1 bear shaped maintain towel. With these organizer bins, your refrigerator, kitchen cabinet, pantry, bedroom, bathroom will be more neatly.', 'images': 'https://m.media-amazon.com/images/I/51Mx3P--hwL._AC_.jpg', 'rating_number': 183, 'price': 27.87, 'average_rating': 4.3, 'parent_asin': 'B0C4PSMDZD'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=36, version=0, score=0.29426473, payload={'description': 'Egg Holder for Refrigerator Drawer - Fridge Egg Drawer Organizer with Whisk Fridge Egg Holder with Silicone Wire Whisk Egg Trays for Refrigerator Egg Container【PULL OUT Egg Drawer with Whisk】- The set comes with 1 Pack of refrigerator egg drawer and 1 Pack of silicone wire whisk. The extended handle of egg holder makes it easy to pull in and out, which is convenient when storing egg. The egg drawers slide out without removing entire bracket. Clear material design keeps food items visible and easy to locate. Easy installation, no tools required. The wire whisk is covered in silicone to prevent damage to pans with a stainless steel handle for comfort. 【Please Note】- Please make sure that the length of your refrigerator shelf is between 11.8-16.5 inches, and the thickness of the shelf must be under 0.6 inches. The fridge egg drawer size: L11.8" x W 7.9" x H 2", the upper part has a smooth spring pull rod design, which can freely adjust the length of the railing. The length of the slide rail can be extended from 11.8 inches to 16.5 inches. The egg holder can fit most standard size refrigerators. 【Premium Material】- The fridge egg organizer is made of food grade PET plastic, which is BPA free, non-toxic, durable, smooth edges and safe to use. The pull-out fridge egg holder drawer keeps eggs handy and out of the way, ideal for organizing your refrigerator. The wire whisk is made of BPA free silicone and stainless steel, which is solid and heat resistant up to 450 degrees Fahrenheit, perfect for cooking almost any meal. 【AUTOMATIC ROLLING】 - The automatic rolling curve design is easy to take, after removing an egg at the front, the egg at the back will automatically roll up. The refrigerator drawer organizer is perfect for organizing eggs in the fridge. The egg holder for refrigerator can keep your eggs fresh for longer periods and better protected without damage or break. 【Space Saver】- The egg organizer for refrigerator is convenient to use in fridge, freezers, kitchen cabinets. It is a great way to add storage and organize, ideal for sort and store eggs. Also great for holding small fruits and vegetables. If you are not happy with the product for any reason, please do not hesitate to contact us. All issues will be solved within 24 hours.', 'images': 'https://m.media-amazon.com/images/I/513WvVoH-uL._AC_.jpg', 'rating_number': 172, 'price': 18.99, 'average_rating': 4.3, 'parent_asin': 'B0B68GGQXT'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=13, version=0, score=0.2850464, payload={'description': 'Nefish Mini Fridge Stand Adjustable Refrigerator Stand with 4 Strong Feet Universal Stand Base Washing Machine Stand Washer and Dryer Pedestals Multi-Functional Base for Appliance (Grey)GREAT FAMILY HELPER - Worry about dripping water or potential danger when put the fridge on carpets, annoy by the distance of dryer to destination? Nefish mobile furniture stand base can help you solve these problem, make home life easier. DOUBLE SIZE ADJUSTMENT - With adjustable steel poles and feet, Nefish black appliance base stand can be adjusted from 16 inches to 24-3/8 inches (width and length), from 4 inches to 6 inches (heights) fit different appliances and furniture. EASY TO ASSEMBLE - The mobile base set includes 4 strong feet(no wheels), what you need to do just to install the connecting rod and the feet. The stand can be easily assembled with instruction. No tool requirement. WIDE APPLICATIONS - Nefish appliance pedestal can load capacity up to 400 lbs. Ideal as the bottom of portable washing machines, washing machines and dryers, refrigerators, mini refrigerators or other household appliances. PREMIUM SERVICE - To ensure the furniture base quality, we will arrange personnel to carefully check the products, only the item passed the inspection can be delivery. If you have any problem( before-service and after service) about the product, pls feel free to tell us, we will reply you within 24 hours.', 'images': 'https://m.media-amazon.com/images/I/41NJ3OvCewL._AC_.jpg', 'rating_number': 699, 'price': 24.99, 'average_rating': 4.4, 'parent_asin': 'B0BHNTM7G6'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=7, version=0, score=0.28367546, payload={'description': "Refrigerator Drip Catcher Tray: Cuttable Refrigerator Drip Tray for Fridge Water Dispenser, Absorbent Drip Tray, Refrigerator Accessories for Whirlpool, GE, Samsung (4PCS, Black) (Semi-Circular)Make Fridge Tray Neat and Free Your Hands: Are you tired from wiping the water stain on the fridge drip tray? The refrigerator drip pan can help you catch the drips or spills effectively from water dispenser. Water stains will not gather on the fridge tray and don't need to wipe it out anymore. Anti-slip Design: The bottom of refrigerator drip trays is designed with anti-slip rubber, so the fridge water catcher mat can stay in place when opening or closing the fridge door. Cut to Fit: The size of refrigerator drip catcher is 8.3 x 3.7 inches which can fit most refrigerator water trays. If the size is unsuitable, you can use scissors to cut the drip catcher tray to fit your refrigerator. Super Absorbent & Dry Quickly: The upper layer of the pad is the absorbent leather, and the middle is diatomite ingredients material which can absorb more drips and dry quickly. This fridge drip catcher can also be a good decoration for your refrigerator and look more modern than other materials. Care Instruction: If refrigerator ice dispenser mat can not absorb more water, please replace and do the wash for it. You can wipe it by a towel or rinse it, hang to air-dry, but do not twist or contort it to dry because of its leather and diatomite materials.", 'images': 'https://m.media-amazon.com/images/I/41h16MwhkZL._AC_.jpg', 'rating_number': 353, 'price': 14.99, 'average_rating': 4.5, 'parent_asin': 'B0BGNFZ122'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=30, version=0, score=0.28314608, payload={'description': 'Ambergron 12 Eggs Holder for Refrigerator, Clear Egg Container for Fridge, Kitchen 2Pack【Perfect for Fridge】 Clear containers are better looking and make it easy to take stock of what you have and how much of it. 【12 Eggs Holder】 Fits for one dozen of eggs. Keep your fridge neat and organized. 【Stackable Organizer】 Storing as much as eggs you want with two or more holders stacked. 【BPA-Free】 Made with solid and food friendly plastic, easily to clean with soap and water. Not Dishwasher Safe 【Fit for Most of Fridges】 This eggs holder is 12.2"*4.7"*3.1"H, fit for most of fridges.', 'images': 'https://m.media-amazon.com/images/I/41JSMkTT1sL._AC_.jpg', 'rating_number': 596, 'price': 18.99, 'average_rating': 4.6, 'parent_asin': 'B09TL8ZPQM'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=0, version=0, score=0.28016636, payload={'description': "Gevi Household V2.0 Countertop Nugget Ice Maker | Self Cleaning Pellet Ice Machine | Open and Pour Water Refill | Store Ice Up to 24 Hours | Stainless Steel Housing | Fits Under Wall Cabinet | White【Nugget Ice】 Also known as Pellet ice or Chewblet ice. Unlike those hard ice cubes, nugget ice is made not only to cool down drinks but also to retain their flavor and provide chewable joy. Before you have to drive to chain stores for it, but now you can have it directly from your countertop whenever you like! 【Ice Ready Always】 Max 30Lbs ice in 24 hours, 4.8Lbs ice basket, 2.8L/3quarts water reservoir, extra thick insulation, auto ice refill, ice is always ready for you. 【Ultra Quiet】 Equipped with latest high performance compressor, muted exhaust fan and high precision ice making components, every effort is made to lower the noise and create an ultra quiet world of ice. 【Sleek Design】 Stainless steel housing, touch control panel, ice access from the front with Anti Dripping Lid, 16.9'' height fits perfectly under wall cabinet. 【100% Satisfaction Is Our Goal】 Gevi values your satisfaction. Every Gevi product (purchased via an official or authorized channel) is entitled to a 12-month warranty and lifetime tech support. If you encounter any issue with Gevi ice maker, please feel free to contact us.", 'images': 'https://m.media-amazon.com/images/I/31CY3buX56L.jpg', 'rating_number': 148, 'price': 509.99, 'average_rating': 4.1, 'parent_asin': 'B0B4G58R7X'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=43, version=0, score=0.26835537, payload={'description': 'Portable Air Conditioner, 5000mAh Rechargeable Battery Operated, 120° Oscillation 700ml Water Tank with 3 Wind Speeds, Perfect for Bedroom, Home, Office,Pearl White【Instant Cool】Unlike the traditioner air conditioner, this portable air cooler sprays mist to cool your down, has low power consumption(10W), very efficient 【Built-in 5000 mAh Battery】 Up to 9h running after a full charge, you can easily charge it through USB devices, charging cable included 【700ml Water Tank】 personal air conditioner with a large water tank, easy to add water from the top and check the capacity from the side, lasts up to 12 hours with a full fill 【3 Adjustable Airflow and Cooling Levels】there are 3 different levels for wind speeds and misting levels, spraying cool mist according to your needs, you can also add some ice into the tank for a colder breeze 【Portable Design】Very lightweight, you can easily carry it with the handle on the top. Compact size fits into most places, you can place it on the desktop, shelf, etc Wattage: 10.0 watts', 'images': 'https://m.media-amazon.com/images/I/41NPbXcoxFL._AC_.jpg', 'rating_number': 267, 'price': None, 'average_rating': 2.8, 'parent_asin': 'B0B6ZWBW5L'}, vector=None, shard_key=None, order_value=None)]